-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hive_prod
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 12 of 12
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ GRANT/DENY CONFLICT: 3 principal(s) have both a GRANT
-- and a DENY on the same table. In UC (additive model), GRANTs are permanent —
-- there is no DENY mechanism. The deny advisory below has NO effect unless either:
--   (a) the GRANT is revoked, or
--   (b) column masks are applied to restrict what the principal can see.
--   Affected: sales_team on sales.customers
--   Affected: sales_team on sales.orders
--   Affected: sales_team on sales.products

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_team
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `sales_team`;
GRANT MODIFY ON TABLE `main`.`sales`.`customers` TO `sales_team`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: data_analysts
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `data_analysts`;
GRANT MODIFY ON TABLE `main`.`sales`.`customers` TO `data_analysts`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_manager@company.com
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `sales_manager@company.com`;
GRANT MODIFY ON TABLE `main`.`sales`.`customers` TO `sales_manager@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_team
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`orders` TO `sales_team`;
GRANT MODIFY ON TABLE `main`.`sales`.`orders` TO `sales_team`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: data_analysts
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`orders` TO `data_analysts`;
GRANT MODIFY ON TABLE `main`.`sales`.`orders` TO `data_analysts`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_manager@company.com
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`orders` TO `sales_manager@company.com`;
GRANT MODIFY ON TABLE `main`.`sales`.`orders` TO `sales_manager@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_team
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`products` TO `sales_team`;
GRANT MODIFY ON TABLE `main`.`sales`.`products` TO `sales_team`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: data_analysts
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`products` TO `data_analysts`;
GRANT MODIFY ON TABLE `main`.`sales`.`products` TO `data_analysts`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: GRANT | Principal: sales_manager@company.com
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`products` TO `sales_manager@company.com`;
GRANT MODIFY ON TABLE `main`.`sales`.`products` TO `sales_manager@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: DENY | Principal: sales_team
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.sales.customers for sales_team
--
-- RECOMMENDED ACTIONS:
-- 1. Remove sales_team from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: DENY | Principal: sales_team
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.sales.orders for sales_team
--
-- RECOMMENDED ACTIONS:
-- 1. Remove sales_team from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: sales_schema_full_access (Ranger ID: 2)
-- Type: DENY | Principal: sales_team
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.sales.products for sales_team
--
-- RECOMMENDED ACTIONS:
-- 1. Remove sales_team from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place
