-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hive_prod
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 1 of 1
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: customer_table_select (Ranger ID: 1)
-- Type: GRANT | Principal: analyst1@company.com
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `analyst1@company.com`;
