-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: access_complex
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 18 of 18
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: all_employees
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `sales`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `all_employees`;
GRANT USE SCHEMA ON SCHEMA `main`.`sales` TO `all_employees`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`sales`.`%s` TO `all_employees`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: all_employees
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `marketing`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `all_employees`;
GRANT USE SCHEMA ON SCHEMA `main`.`marketing` TO `all_employees`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`marketing`.`%s` TO `all_employees`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: all_employees
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `finance`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `all_employees`;
GRANT USE SCHEMA ON SCHEMA `main`.`finance` TO `all_employees`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`finance`.`%s` TO `all_employees`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_engineering
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `sales`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_engineering`;
GRANT USE SCHEMA ON SCHEMA `main`.`sales` TO `data_engineering`;
GRANT CREATE TABLE ON SCHEMA `main`.`sales` TO `data_engineering`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`sales` TO `data_engineering`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`sales`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`sales`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`sales` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: platform_team
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `sales`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `platform_team`;
GRANT USE SCHEMA ON SCHEMA `main`.`sales` TO `platform_team`;
GRANT CREATE TABLE ON SCHEMA `main`.`sales` TO `platform_team`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`sales` TO `platform_team`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`sales`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`sales`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`sales` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_admin@company.com
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `sales`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_admin@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`sales` TO `data_admin@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`sales` TO `data_admin@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`sales` TO `data_admin@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`sales`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `sales` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'sales'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`sales`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`sales` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_engineering
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `marketing`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_engineering`;
GRANT USE SCHEMA ON SCHEMA `main`.`marketing` TO `data_engineering`;
GRANT CREATE TABLE ON SCHEMA `main`.`marketing` TO `data_engineering`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`marketing` TO `data_engineering`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`marketing`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`marketing`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`marketing` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: platform_team
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `marketing`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `platform_team`;
GRANT USE SCHEMA ON SCHEMA `main`.`marketing` TO `platform_team`;
GRANT CREATE TABLE ON SCHEMA `main`.`marketing` TO `platform_team`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`marketing` TO `platform_team`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`marketing`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`marketing`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`marketing` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_admin@company.com
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `marketing`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_admin@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`marketing` TO `data_admin@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`marketing` TO `data_admin@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`marketing` TO `data_admin@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`marketing`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `marketing` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'marketing'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`marketing`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`marketing` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_engineering
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `finance`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_engineering`;
GRANT USE SCHEMA ON SCHEMA `main`.`finance` TO `data_engineering`;
GRANT CREATE TABLE ON SCHEMA `main`.`finance` TO `data_engineering`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`finance` TO `data_engineering`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`finance`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`finance`.`%s` TO `data_engineering`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`finance` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: platform_team
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `finance`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `platform_team`;
GRANT USE SCHEMA ON SCHEMA `main`.`finance` TO `platform_team`;
GRANT CREATE TABLE ON SCHEMA `main`.`finance` TO `platform_team`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`finance` TO `platform_team`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`finance`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`finance`.`%s` TO `platform_team`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`finance` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: GRANT | Principal: data_admin@company.com
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `finance`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data_admin@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`finance` TO `data_admin@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`finance` TO `data_admin@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`finance` TO `data_admin@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`finance`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `finance` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`finance`.`%s` TO `data_admin@company.com`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on SCHEMA `main`.`finance` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: external_vendors
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.sales.* for external_vendors
--
-- RECOMMENDED ACTIONS:
-- 1. Remove external_vendors from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: contractor1@company.com
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.sales.* for contractor1@company.com
--
-- RECOMMENDED ACTIONS:
-- 1. Remove contractor1@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: external_vendors
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.marketing.* for external_vendors
--
-- RECOMMENDED ACTIONS:
-- 1. Remove external_vendors from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: contractor1@company.com
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.marketing.* for contractor1@company.com
--
-- RECOMMENDED ACTIONS:
-- 1. Remove contractor1@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: external_vendors
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.finance.* for external_vendors
--
-- RECOMMENDED ACTIONS:
-- 1. Remove external_vendors from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: enterprise_data_governance (Ranger ID: 3)
-- Type: DENY | Principal: contractor1@company.com
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.finance.* for contractor1@company.com
--
-- RECOMMENDED ACTIONS:
-- 1. Remove contractor1@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place
