-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: cm_hbase
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 53 of 53
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: pr00_xbgdta
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `pr00_xbgdta`;
GRANT MODIFY ON TABLE `main`.`default`.`prospects` TO `pr00_xbgdta`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`prospects` TO `pr00_xbgdta`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`prospects` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: hbase
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `hbase@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`prospects` TO `hbase@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`prospects` TO `hbase@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`prospects` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `hive@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`prospects` TO `hive@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`prospects` TO `hive@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`prospects` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: pr00_xbgdta
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `pr00_xbgdta`;
GRANT MODIFY ON TABLE `main`.`default`.`invoices` TO `pr00_xbgdta`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`invoices` TO `pr00_xbgdta`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`invoices` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: hbase
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `hbase@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`invoices` TO `hbase@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`invoices` TO `hbase@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`invoices` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `hive@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`invoices` TO `hive@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`invoices` TO `hive@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`invoices` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: rangerlookup
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `rangerlookup@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: rangerlookup
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `rangerlookup@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: qqsens
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `qqsens`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: fb00_xbgdta
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`prospects` TO `fb00_xbgdta`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: qqsens
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `qqsens`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: all - table, column-family, column (Ranger ID: 4)
-- Type: HBASE_GRANT | Principal: fb00_xbgdta
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`invoices` TO `fb00_xbgdta`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: ATLAS_HBASE_TABLES (Ranger ID: 5)
-- Type: HBASE_GRANT | Principal: atlas
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`atlas_janus` TO `atlas@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`atlas_janus` TO `atlas@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`atlas_janus` TO `atlas@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: ATLAS_HBASE_TABLES (Ranger ID: 5)
-- Type: HBASE_GRANT | Principal: atlas
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`ATLAS_ENTITY_AUDIT_EVENTS` TO `atlas@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`ATLAS_ENTITY_AUDIT_EVENTS` TO `atlas@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`ATLAS_ENTITY_AUDIT_EVENTS` TO `atlas@company.com`;
-- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.

-- ═══════════════════════════════════════════════════════
-- Policy: SYSTEM (Ranger ID: 782)
-- Type: HBASE_GRANT | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ PRINCIPAL NOT TRANSLATED — Ranger {USER} wildcard
-- Policy: SYSTEM
-- Resource: `main`.`SYSTEM`
-- Original principal: {USER}
--
-- {USER} is a Ranger placeholder meaning 'the currently authenticated user'.
-- It cannot be used as a named principal in a UC GRANT statement.
--
-- If the intent is 'grant to all users': use GRANT ... TO `account users`.
-- If the intent is 'row/column access based on the calling user': express
-- the logic in a row filter or column mask using current_user().

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda017 (Ranger ID: 821)
-- Type: HBASE_GRANT | Principal: fb00_xda017
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da017*  →  SQL LIKE: 'fb00_%da017%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da017%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda017`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda017`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda017`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda017 (Ranger ID: 821)
-- Type: HBASE_GRANT | Principal: xagcla
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da017*  →  SQL LIKE: 'fb00_%da017%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da017%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `xagcla`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `xagcla`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `xagcla`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda029 (Ranger ID: 822)
-- Type: HBASE_GRANT | Principal: fb00_xda029
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da029*  →  SQL LIKE: 'fb00_%da029%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da029%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda029`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda029`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda029`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda034 (Ranger ID: 823)
-- Type: HBASE_GRANT | Principal: fb00_xda034
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da034*  →  SQL LIKE: 'fb00_%da034%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da034%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda034`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda034`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda034`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda035 (Ranger ID: 824)
-- Type: HBASE_GRANT | Principal: fb00_xda035
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da035*  →  SQL LIKE: 'fb00_%da035%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da035%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda035`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda035`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda035`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda041 (Ranger ID: 825)
-- Type: HBASE_GRANT | Principal: fb00_xda041
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da041*  →  SQL LIKE: 'fb00_%da041%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da041%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda041`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda041`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda041`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda043 (Ranger ID: 826)
-- Type: HBASE_GRANT | Principal: fb00_xda043
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da043*  →  SQL LIKE: 'fb00_%da043%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da043%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda043`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda043`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda043`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda052 (Ranger ID: 827)
-- Type: HBASE_GRANT | Principal: fb00_xda052
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da052*  →  SQL LIKE: 'fb00_%da052%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da052%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda052`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda052`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda052`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda060 (Ranger ID: 828)
-- Type: HBASE_GRANT | Principal: fb00_xda060
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da060*  →  SQL LIKE: 'fb00_%da060%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da060%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda060`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda060`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda060`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda066 (Ranger ID: 829)
-- Type: HBASE_GRANT | Principal: fb00_xda066
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da066*  →  SQL LIKE: 'fb00_%da066%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da066%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda066`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda066`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda066`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda085 (Ranger ID: 830)
-- Type: HBASE_GRANT | Principal: fb00_xda085
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da085*  →  SQL LIKE: 'fb00_%da085%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da085%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda085`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda085`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda085`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda092 (Ranger ID: 831)
-- Type: HBASE_GRANT | Principal: fb00_xda092
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da092*  →  SQL LIKE: 'fb00_%da092%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da092%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda092`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda092`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda092`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda126 (Ranger ID: 832)
-- Type: HBASE_GRANT | Principal: fb00_xda126
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da126*  →  SQL LIKE: 'fb00_%da126%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da126%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda126`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda126`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda126`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xda126 (Ranger ID: 832)
-- Type: HBASE_GRANT | Principal: fb00_xda085
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*da126*  →  SQL LIKE: 'fb00_%da126%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%da126%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda085`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xds020 (Ranger ID: 833)
-- Type: HBASE_GRANT | Principal: fb00_xds020
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*ds020*  →  SQL LIKE: 'fb00_%ds020%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%ds020%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xds020`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xds020`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xds020`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xoi022
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi022`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi022`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi022`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_braff
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_braff`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_braff`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_bbrut
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_bbrut`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_bbrut`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xoi099
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi099`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xoi098
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi098`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xoi097
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi097`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: sd00_xlx001
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `sd00_xlx001`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda085
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda085`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda126
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda126`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda017
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda017`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: qqsens
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `qqsens`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda062
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda062`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xpr203
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xpr203`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda144
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda144`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda143
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda143`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda108
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda108`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xoi033
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi033`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda042
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda042`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xpx091
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xpx091`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi022 (Ranger ID: 834)
-- Type: HBASE_GRANT | Principal: fb00_xda107
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi022*  →  SQL LIKE: 'fb00_%oi022%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi022%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xda107`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi025 (Ranger ID: 835)
-- Type: HBASE_GRANT | Principal: fb00_xoi025
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi025*  →  SQL LIKE: 'fb00_%oi025%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi025%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi025`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi025`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi025`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi033 (Ranger ID: 836)
-- Type: HBASE_GRANT | Principal: fb00_xoi033
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi033*  →  SQL LIKE: 'fb00_%oi033%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi033%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi033`';
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi033`';
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xoi033`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: fb00_xoi033 (Ranger ID: 836)
-- Type: HBASE_GRANT | Principal: fb00_xpr203
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fb00_*oi033*  →  SQL LIKE: 'fb00_%oi033%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'fb00_%oi033%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fb00_xpr203`';
    -- ⚠ EXECUTE privilege is only valid on UC functions, not on tables or schemas. No GRANT is emitted. Use a UDF policy resource to grant EXECUTE on a specific function.
  END FOR;
END;
