-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: masking_medium
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 9 of 9
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 3 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `customer_360`.`customers`.email have been combined.
-- Principals merged (3): support_team, analytics_team, contractors
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`customer_360`.mask_customers_email(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN IS_ACCOUNT_GROUP_MEMBER('support_team') THEN CONCAT(LEFT(val, 4), '***')
    WHEN IS_ACCOUNT_GROUP_MEMBER('analytics_team') THEN SHA2(val, 256)
    WHEN IS_ACCOUNT_GROUP_MEMBER('contractors') THEN NULL
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`customer_360`.`customers`
ALTER COLUMN email SET MASK `main`.`customer_360`.mask_customers_email;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `customer_360`.`customers`.phone have been combined.
-- Principals merged (3): support_team, analytics_team, contractors
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`customer_360`.mask_customers_phone(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN IS_ACCOUNT_GROUP_MEMBER('support_team') THEN CONCAT(LEFT(val, 4), '***')
    WHEN IS_ACCOUNT_GROUP_MEMBER('analytics_team') THEN SHA2(val, 256)
    WHEN IS_ACCOUNT_GROUP_MEMBER('contractors') THEN NULL
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`customer_360`.`customers`
ALTER COLUMN phone SET MASK `main`.`customer_360`.mask_customers_phone;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `customer_360`.`customers`.credit_card have been combined.
-- Principals merged (3): support_team, analytics_team, contractors
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`customer_360`.mask_customers_credit_card(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN IS_ACCOUNT_GROUP_MEMBER('support_team') THEN CONCAT(LEFT(val, 4), '***')
    WHEN IS_ACCOUNT_GROUP_MEMBER('analytics_team') THEN SHA2(val, 256)
    WHEN IS_ACCOUNT_GROUP_MEMBER('contractors') THEN NULL
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`customer_360`.`customers`
ALTER COLUMN credit_card SET MASK `main`.`customer_360`.mask_customers_credit_card;
