-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hive_prod
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 1 of 1
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: ssn_masking (Ranger ID: 201)
-- Type: COLUMN_MASK | Principal: hr_staff
-- ═══════════════════════════════════════════════════════
-- Column Mask: Show last 4 characters for hr_staff
CREATE OR REPLACE FUNCTION `main`.`hr`.mask_employees_ssn_hr_staff(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('hr_staff'),
  CONCAT('***-**-', RIGHT(val, 4)),
  val
);

ALTER TABLE `main`.`hr`.`employees`
ALTER COLUMN ssn SET MASK `main`.`hr`.mask_employees_ssn_hr_staff;
