-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: masking_complex
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 32 of 32
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 8 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`transactions`.account_number have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_transactions_account_number(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`transactions`
ALTER COLUMN account_number SET MASK `main`.`finance`.mask_transactions_account_number;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`transactions`.transaction_amount have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_transactions_transaction_amount(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⚠ Auto-adapted: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time); Column reference `transaction_amount` → `val` (the mask function parameter)
    -- Original: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN CASE WHEN val < 1000 THEN val ELSE NULL END
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`transactions`
ALTER COLUMN transaction_amount SET MASK `main`.`finance`.mask_transactions_transaction_amount;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`transactions`.customer_id have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_transactions_customer_id(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`transactions`
ALTER COLUMN customer_id SET MASK `main`.`finance`.mask_transactions_customer_id;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`transactions`.birth_date have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_transactions_birth_date(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`transactions`
ALTER COLUMN birth_date SET MASK `main`.`finance`.mask_transactions_birth_date;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`accounts`.account_number have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_accounts_account_number(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`accounts`
ALTER COLUMN account_number SET MASK `main`.`finance`.mask_accounts_account_number;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`accounts`.transaction_amount have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_accounts_transaction_amount(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⚠ Auto-adapted: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time); Column reference `transaction_amount` → `val` (the mask function parameter)
    -- Original: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN CASE WHEN val < 1000 THEN val ELSE NULL END
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`accounts`
ALTER COLUMN transaction_amount SET MASK `main`.`finance`.mask_accounts_transaction_amount;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`accounts`.customer_id have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_accounts_customer_id(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`accounts`
ALTER COLUMN customer_id SET MASK `main`.`finance`.mask_accounts_customer_id;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `finance`.`accounts`.birth_date have been combined.
-- Principals merged (4): junior_analysts, marketing_team, audit_team, finance_leadership
-- Function parameter is STRING. If the actual column type differs, adjust the signature.
-- DATE_YEAR branches use TRY_CAST(val AS DATE) — verify the column holds date strings.
-- ⚠ Custom Ranger valueExpr detected. Auto-adaptation is attempted:
--   • CAST('<non-numeric>' AS <type>) → NULL
--   • Bare column references matching the masked column → val
--   Branches with cross-column references (other columns) cannot be adapted —
--   they use a '***REDACTED***' fallback and must be rewritten manually.

CREATE OR REPLACE FUNCTION `main`.`finance`.mask_accounts_birth_date(val STRING)
RETURNS STRING
RETURN
  CASE
    -- ⛔ BRANCH OMITTED — custom expression has cross-column references (principal: junior_analysts)
    --   Original Ranger expression: CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE CAST('XXXXX' AS DECIMAL) END
    --   Issue: Cross-column reference(s): transaction_amount. UC mask functions can only access 'val' (the current column value) — other column references cannot be resolved at mask-evaluation time. Rewrite this branch manually.
    --   Partial fixes applied: CAST('XXXXX' AS DECIMAL) → NULL ('XXXXX' is not a valid DECIMAL — would fail at parse time)
    --   Partially adapted (still not valid): CASE WHEN transaction_amount < 1000 THEN transaction_amount ELSE NULL END
    --   ACTION REQUIRED: Replace the WHEN branch below with a valid UC expression.
    -- WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN <rewrite this expression manually>
    WHEN IS_ACCOUNT_GROUP_MEMBER('junior_analysts') THEN '***REDACTED***'  -- conservative fallback, rewrite before executing
    WHEN IS_ACCOUNT_GROUP_MEMBER('marketing_team') THEN CAST(MAKE_DATE(YEAR(TRY_CAST(val AS DATE)), 1, 1) AS STRING)
    WHEN IS_ACCOUNT_GROUP_MEMBER('audit_team') THEN CONCAT('***-**-', RIGHT(val, 4))
    WHEN IS_ACCOUNT_GROUP_MEMBER('finance_leadership') THEN val  -- MASK_NONE: no masking for this principal
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`finance`.`accounts`
ALTER COLUMN birth_date SET MASK `main`.`finance`.mask_accounts_birth_date;
