-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: rowfilter_simple
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 1 of 1
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: regional_sales_filter (Ranger ID: 101)
-- Type: ROW_FILTER | Principal: west_manager@company.com
-- ═══════════════════════════════════════════════════════
-- Row Filter for: west_manager@company.com
-- Original expression: region = 'WEST'

CREATE OR REPLACE FUNCTION `main`.`sales`.rf_orders_west_manager_company_com(region STRING)
RETURNS BOOLEAN
RETURN IF(
  current_user() = 'west_manager@company.com',
  region = 'WEST',
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`sales`.`orders`
SET ROW FILTER `main`.`sales`.rf_orders_west_manager_company_com ON (region);
