-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: rowfilter_complex
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 2 of 2
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 1 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `customer_360`.`customer_details` have been combined into one function.
-- Principals merged (2): customer_success, account_managers
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`customer_360`.rf_customer_details(country STRING, customer_tier STRING, consent_given STRING, assigned_to STRING, team_id STRING, user_teams STRING, user_name STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN IS_ACCOUNT_GROUP_MEMBER('customer_success') THEN country IN ('USA', 'CAN') AND customer_tier IN ('GOLD', 'PLATINUM') AND consent_given = TRUE
    WHEN IS_ACCOUNT_GROUP_MEMBER('account_managers') THEN (assigned_to = CURRENT_USER() OR team_id IN (SELECT team_id FROM user_teams WHERE user_name = CURRENT_USER()))
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`customer_360`.`customer_details`
SET ROW FILTER `main`.`customer_360`.rf_customer_details ON (country, customer_tier, consent_given, assigned_to, team_id, user_teams, user_name);
