-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hive_prod
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 1 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `sales`.`transactions` have been combined into one function.
-- Principals merged (3): regional_managers, sales_analysts, executives
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`sales`.rf_transactions(region STRING, order_date STRING, department STRING, status STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN IS_ACCOUNT_GROUP_MEMBER('regional_managers') THEN region IN ('WEST', 'CENTRAL') AND order_date >= '2024-01-01'
    WHEN IS_ACCOUNT_GROUP_MEMBER('sales_analysts') THEN department = 'SALES' AND status = 'ACTIVE'
    WHEN IS_ACCOUNT_GROUP_MEMBER('executives') THEN TRUE
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`sales`.`transactions`
SET ROW FILTER `main`.`sales`.rf_transactions ON (region, order_date, department, status);
