-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: tag_prod
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 7 of 7
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — sales.customers.ssn (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`sales`.`customers`
  ALTER COLUMN `ssn` SET TAGS ('PII' = 'true', 'level' = 'high', 'category' = 'sensitive');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — sales.customers.email (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`sales`.`customers`
  ALTER COLUMN `email` SET TAGS ('PII' = 'true', 'level' = 'high', 'category' = 'sensitive');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — hr.employees.salary (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`hr`.`employees`
  ALTER COLUMN `salary` SET TAGS ('PII' = 'true', 'level' = 'high', 'category' = 'sensitive');

-- ═══════════════════════════════════════════════════════
-- Policy: pii_tag_access (Ranger ID: 301)
-- Type: TAG_GRANT | Principal: data_protection_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII)
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `data_protection_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: pii_tag_access (Ranger ID: 301)
-- Type: TAG_GRANT | Principal: legal
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII)
GRANT SELECT ON TABLE `main`.`sales`.`customers` TO `legal`;

-- ═══════════════════════════════════════════════════════
-- Policy: pii_tag_access (Ranger ID: 301)
-- Type: TAG_GRANT | Principal: data_protection_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII)
GRANT SELECT ON TABLE `main`.`hr`.`employees` TO `data_protection_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: pii_tag_access (Ranger ID: 301)
-- Type: TAG_GRANT | Principal: legal
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII)
GRANT SELECT ON TABLE `main`.`hr`.`employees` TO `legal`;
