-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: tag_complex
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 39 of 39
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — finance.accounts.account_balance (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`finance`.`accounts`
  ALTER COLUMN `account_balance` SET TAGS ('FINANCIAL' = 'true', 'classification' = 'confidential', 'sox_applicable' = 'true', 'SOX' = 'true', 'regulation' = 'Sarbanes-Oxley', 'audit_required' = 'true');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — finance.transactions.credit_card (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`finance`.`transactions`
  ALTER COLUMN `credit_card` SET TAGS ('PCI_DSS' = 'true', 'regulation' = 'Payment Card Industry', 'encryption_required' = 'true', 'SENSITIVE' = 'true', 'classification' = 'restricted');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — customer_360.customers.email (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`customer_360`.`customers`
  ALTER COLUMN `email` SET TAGS ('PII' = 'true', 'classification' = 'restricted', 'gdpr_applicable' = 'true');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — customer_360.customers_eu.email (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`customer_360`.`customers_eu`
  ALTER COLUMN `email` SET TAGS ('PII' = 'true', 'classification' = 'restricted', 'gdpr_applicable' = 'true', 'PII_EU' = 'true', 'geography' = 'EU');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — hr.payroll.salary (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`hr`.`payroll`
  ALTER COLUMN `salary` SET TAGS ('FINANCIAL' = 'true', 'classification' = 'restricted', 'sox_applicable' = 'true', 'SENSITIVE' = 'true', 'encryption_required' = 'true');

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: data_protection_officers
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers` TO `data_protection_officers`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers` TO `data_protection_officers`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: privacy_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers` TO `privacy_team`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers` TO `privacy_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: dpo@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers` TO `dpo@company.com`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers` TO `dpo@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: data_protection_officers
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers_eu` TO `data_protection_officers`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers_eu` TO `data_protection_officers`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: privacy_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers_eu` TO `privacy_team`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers_eu` TO `privacy_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: dpo@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`customer_360`.`customers_eu` TO `dpo@company.com`;
GRANT MODIFY ON TABLE `main`.`customer_360`.`customers_eu` TO `dpo@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: data_protection_officers
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `data_protection_officers`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `data_protection_officers`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: privacy_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `privacy_team`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `privacy_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: dpo@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `dpo@company.com`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `dpo@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: data_protection_officers
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `data_protection_officers`;
GRANT MODIFY ON TABLE `main`.`hr`.`payroll` TO `data_protection_officers`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: privacy_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `privacy_team`;
GRANT MODIFY ON TABLE `main`.`hr`.`payroll` TO `privacy_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: dpo@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `dpo@company.com`;
GRANT MODIFY ON TABLE `main`.`hr`.`payroll` TO `dpo@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: data_protection_officers
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `data_protection_officers`;
GRANT MODIFY ON TABLE `main`.`finance`.`transactions` TO `data_protection_officers`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: privacy_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `privacy_team`;
GRANT MODIFY ON TABLE `main`.`finance`.`transactions` TO `privacy_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: TAG_GRANT | Principal: dpo@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PII, PII_EU, FINANCIAL, SENSITIVE)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `dpo@company.com`;
GRANT MODIFY ON TABLE `main`.`finance`.`transactions` TO `dpo@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: ROW_FILTER | Principal: marketing_team
-- ═══════════════════════════════════════════════════════
-- Row Filter for: marketing_team
-- Original expression: consent_given = TRUE AND data_retention_date > CURRENT_DATE()

CREATE OR REPLACE FUNCTION `main`.`customer_360`.rf_customers_marketing_team(consent_given STRING, data_retention_date STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('marketing_team'),
  consent_given = TRUE AND data_retention_date > CURRENT_DATE(),
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`customer_360`.`customers`
SET ROW FILTER `main`.`customer_360`.rf_customers_marketing_team ON (consent_given, data_retention_date);

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: ROW_FILTER | Principal: marketing_team
-- ═══════════════════════════════════════════════════════
-- Row Filter for: marketing_team
-- Original expression: consent_given = TRUE AND data_retention_date > CURRENT_DATE()

CREATE OR REPLACE FUNCTION `main`.`customer_360`.rf_customers_eu_marketing_team(consent_given STRING, data_retention_date STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('marketing_team'),
  consent_given = TRUE AND data_retention_date > CURRENT_DATE(),
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`customer_360`.`customers_eu`
SET ROW FILTER `main`.`customer_360`.rf_customers_eu_marketing_team ON (consent_given, data_retention_date);

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: ROW_FILTER | Principal: marketing_team
-- ═══════════════════════════════════════════════════════
-- Row Filter for: marketing_team
-- Original expression: consent_given = TRUE AND data_retention_date > CURRENT_DATE()

CREATE OR REPLACE FUNCTION `main`.`finance`.rf_accounts_marketing_team(consent_given STRING, data_retention_date STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('marketing_team'),
  consent_given = TRUE AND data_retention_date > CURRENT_DATE(),
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`finance`.`accounts`
SET ROW FILTER `main`.`finance`.rf_accounts_marketing_team ON (consent_given, data_retention_date);

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: ROW_FILTER | Principal: marketing_team
-- ═══════════════════════════════════════════════════════
-- Row Filter for: marketing_team
-- Original expression: consent_given = TRUE AND data_retention_date > CURRENT_DATE()

CREATE OR REPLACE FUNCTION `main`.`hr`.rf_payroll_marketing_team(consent_given STRING, data_retention_date STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('marketing_team'),
  consent_given = TRUE AND data_retention_date > CURRENT_DATE(),
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`hr`.`payroll`
SET ROW FILTER `main`.`hr`.rf_payroll_marketing_team ON (consent_given, data_retention_date);

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: ROW_FILTER | Principal: marketing_team
-- ═══════════════════════════════════════════════════════
-- Row Filter for: marketing_team
-- Original expression: consent_given = TRUE AND data_retention_date > CURRENT_DATE()

CREATE OR REPLACE FUNCTION `main`.`finance`.rf_transactions_marketing_team(consent_given STRING, data_retention_date STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('marketing_team'),
  consent_given = TRUE AND data_retention_date > CURRENT_DATE(),
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`finance`.`transactions`
SET ROW FILTER `main`.`finance`.rf_transactions_marketing_team ON (consent_given, data_retention_date);

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: COLUMN_MASK | Principal: analytics_team
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for analytics_team
CREATE OR REPLACE FUNCTION `main`.`customer_360`.mask_customers_email_analytics_team(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('analytics_team'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`customer_360`.`customers`
ALTER COLUMN email SET MASK `main`.`customer_360`.mask_customers_email_analytics_team;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: COLUMN_MASK | Principal: analytics_team
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for analytics_team
CREATE OR REPLACE FUNCTION `main`.`customer_360`.mask_customers_eu_email_analytics_team(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('analytics_team'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`customer_360`.`customers_eu`
ALTER COLUMN email SET MASK `main`.`customer_360`.mask_customers_eu_email_analytics_team;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: COLUMN_MASK | Principal: analytics_team
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for analytics_team
CREATE OR REPLACE FUNCTION `main`.`finance`.mask_accounts_account_balance_analytics_team(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('analytics_team'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`finance`.`accounts`
ALTER COLUMN account_balance SET MASK `main`.`finance`.mask_accounts_account_balance_analytics_team;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: COLUMN_MASK | Principal: analytics_team
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for analytics_team
CREATE OR REPLACE FUNCTION `main`.`hr`.mask_payroll_salary_analytics_team(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('analytics_team'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`hr`.`payroll`
ALTER COLUMN salary SET MASK `main`.`hr`.mask_payroll_salary_analytics_team;

-- ═══════════════════════════════════════════════════════
-- Policy: gdpr_compliance_policy (Ranger ID: 304)
-- Type: COLUMN_MASK | Principal: analytics_team
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for analytics_team
CREATE OR REPLACE FUNCTION `main`.`finance`.mask_transactions_credit_card_analytics_team(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('analytics_team'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`finance`.`transactions`
ALTER COLUMN credit_card SET MASK `main`.`finance`.mask_transactions_credit_card_analytics_team;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: audit_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `audit_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: compliance_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `compliance_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: auditor@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `auditor@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: audit_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `audit_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: compliance_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `compliance_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: auditor@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `auditor@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: audit_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `audit_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: compliance_team
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `compliance_team`;

-- ═══════════════════════════════════════════════════════
-- Policy: financial_regulatory_policy (Ranger ID: 305)
-- Type: TAG_GRANT | Principal: auditor@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: SOX, PCI_DSS, FINANCIAL)
GRANT SELECT ON TABLE `main`.`hr`.`payroll` TO `auditor@company.com`;
