-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: tag_medium
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 10 of 10
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — finance.transactions (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`finance`.`transactions` SET TAGS ('CONFIDENTIAL' = 'true', 'level' = 'high', 'retention_years' = '7');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — sales.reports (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`sales`.`reports` SET TAGS ('INTERNAL' = 'true', 'level' = 'medium', 'retention_years' = '5');

-- ═══════════════════════════════════════════════════════
-- Policy: SET TAGS — marketing.campaigns (Ranger ID: None)
-- Type: TAG_SET | Principal: 
-- ═══════════════════════════════════════════════════════
ALTER TABLE `main`.`marketing`.`campaigns` SET TAGS ('PUBLIC' = 'true', 'level' = 'low', 'retention_years' = '3');

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_governance
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `data_governance`;
GRANT MODIFY ON TABLE `main`.`finance`.`transactions` TO `data_governance`;

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_steward@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`finance`.`transactions` TO `data_steward@company.com`;
GRANT MODIFY ON TABLE `main`.`finance`.`transactions` TO `data_steward@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_governance
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`sales`.`reports` TO `data_governance`;
GRANT MODIFY ON TABLE `main`.`sales`.`reports` TO `data_governance`;

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_steward@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`sales`.`reports` TO `data_steward@company.com`;
GRANT MODIFY ON TABLE `main`.`sales`.`reports` TO `data_steward@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_governance
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`marketing`.`campaigns` TO `data_governance`;
GRANT MODIFY ON TABLE `main`.`marketing`.`campaigns` TO `data_governance`;

-- ═══════════════════════════════════════════════════════
-- Policy: data_classification_policy (Ranger ID: 302)
-- Type: TAG_GRANT | Principal: data_steward@company.com
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: CONFIDENTIAL, INTERNAL, PUBLIC)
GRANT SELECT ON TABLE `main`.`marketing`.`campaigns` TO `data_steward@company.com`;
GRANT MODIFY ON TABLE `main`.`marketing`.`campaigns` TO `data_steward@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: public_data_access (Ranger ID: 303)
-- Type: TAG_GRANT | Principal: all_employees
-- ═══════════════════════════════════════════════════════
-- Tag-based grant (tags: PUBLIC)
GRANT SELECT ON TABLE `main`.`marketing`.`campaigns` TO `all_employees`;
