-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: kafkadev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 15 of 15
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: 10: test-topic publish/consume allowed (Ranger ID: 10)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (PUBLISH, CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ 'PUBLISH' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 101: test-topic publish/consume allowed (Ranger ID: 101)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (PUBLISH, CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user2@company.com`;
-- ⚠ 'PUBLISH' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 102: test-topic publish/consume allowed (Ranger ID: 102)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user3@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user3@company.com`;
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 103: test-topic publish/consume allowed (Ranger ID: 103)
-- Type: GRANT | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user4@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user4@company.com`;
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 103: test-topic publish/consume allowed (Ranger ID: 103)
-- Type: GRANT | Principal: user5
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user5@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user5@company.com`;
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 104: test-topic publish/consume allowed (Ranger ID: 104)
-- Type: GRANT | Principal: user6
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (PUBLISH, CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user6@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user6@company.com`;
-- ⚠ 'PUBLISH' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 02: transation id (Ranger ID: 20)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (PUBLISH) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ 'PUBLISH' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: create/alter access for user1 on cluster-1 (Ranger ID: 30)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`default` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: Alter access for user31 on cluster-2 (Ranger ID: 301)
-- Type: GRANT | Principal: user31
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user31@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user31@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`default` TO `user31@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: Alter access for user32 on cluster-1 (Ranger ID: 302)
-- Type: GRANT | Principal: user32
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ALTER) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user32@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user32@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON SCHEMA `main`.`default` TO `user32@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: delegationtoken (Ranger ID: 40)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (DESCRIBE) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ 'DESCRIBE' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: consumergroup-1 access (Ranger ID: 50)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: consumergroup-2 access for user4 (Ranger ID: 52)
-- Type: GRANT | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user4 on default.None was already emitted above.
-- Original column scope: * (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: 110: test-topic-1/2 consume allowed for user2 (Ranger ID: 110)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CONSUME) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user2@company.com`;
-- ⚠ 'CONSUME' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: 110: new-topic-1/2 allowed for user2 (Ranger ID: 111)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user2 on default.None was already emitted above.
-- Original column scope: * (widened to table-level in UC).
