-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hive
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 43 of 43
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: url=s3a://qe-s3-bucket-mst/test_abcd/abcd; s3a://qe-s3-bucket-mst/demo/*: URL-access-policy (Ranger ID: 200)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: s3a://qe-s3-bucket-mst/test_abcd/abcd (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_s3a___qe_s3_bucket_mst_test_abcd_abcd>` TO `public`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_s3a___qe_s3_bucket_mst_test_abcd_abcd>` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: url=s3a://qe-s3-bucket-mst/test_abcd/abcd; s3a://qe-s3-bucket-mst/demo/*: URL-access-policy (Ranger ID: 200)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: s3a://qe-s3-bucket-mst/demo (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_s3a___qe_s3_bucket_mst_demo>` TO `public`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_s3a___qe_s3_bucket_mst_demo>` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    -- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
    EXECUTE IMMEDIATE format('GRANT MANAGE ON TABLE `main`.`default`.`%s` TO `admin`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for admin on default.test* was already emitted above.
-- Original column scope: * (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tmp; column=tmp* (Ranger ID: 4)
-- Type: GRANT (WILDCARD COLUMN 'tmp*') | Principals: group1, group2, user1, user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT — pattern 'tmp*' → SQL LIKE 'tmp%'
-- Permitted principals: group1, group2, user1@company.com, user2@company.com
-- UC has no column-level GRANT. Strategy: mask matching columns to NULL for non-permitted principals.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR col AS (
    SELECT column_name
    FROM `main`.information_schema.columns
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name     = 'tmp'
      AND column_name LIKE 'tmp%'
  ) DO
    EXECUTE IMMEDIATE format(
      'CREATE OR REPLACE FUNCTION `main`.`db1`.mask_tmp_col_restrict_%s(val STRING) RETURNS STRING RETURN IF(NOT ((IS_ACCOUNT_GROUP_MEMBER(''group1'')) OR (IS_ACCOUNT_GROUP_MEMBER(''group2'')) OR (current_user() = ''user1@company.com'') OR (current_user() = ''user2@company.com'')), NULL, val)',
      col.column_name
    );
    EXECUTE IMMEDIATE format(
      'ALTER TABLE `main`.`db1`.`tmp` ALTER COLUMN `%s` SET MASK `main`.`db1`.mask_tmp_col_restrict_%s',
      col.column_name, col.column_name
    );
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: hiveservice=* (Ranger ID: 5)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (SERVICEADMIN) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ 'SERVICEADMIN' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group1`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo1` TO `group1`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo1`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group2`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo1` TO `group2`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo1`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo1` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo1`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo1` TO `user2@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo1`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo2`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group1`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo2` TO `group1`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo2` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo2'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo2`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo2`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group2`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo2` TO `group2`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo2` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo2'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo2`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo2`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo2` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo2` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo2'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo2`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1,demo2 (Ranger ID: 6)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `demo2`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`demo2` TO `user2@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `demo2` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'demo2'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`demo2`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=demo1; table=demo1_tbl1,demo1_tbl2; column=* (Ranger ID: 7)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.

-- ═══════════════════════════════════════════════════════
-- Policy: db=dummy; table=*; column=* (Ranger ID: 8)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `dummy`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`dummy` TO `user1@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`dummy` TO `user1@company.com`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`dummy` TO `user1@company.com`;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `dummy` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'dummy'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`dummy`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=dummy; table=*; column=* (Ranger ID: 8)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `dummy`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`dummy` TO `user2@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`dummy` TO `user2@company.com`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`dummy` TO `user2@company.com`;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `dummy` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'dummy'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT MODIFY ON TABLE `main`.`dummy`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1 (Ranger ID: 9)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `db1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group1`;
GRANT USE SCHEMA ON SCHEMA `main`.`db1` TO `group1`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `db1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1 (Ranger ID: 9)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `db1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group2`;
GRANT USE SCHEMA ON SCHEMA `main`.`db1` TO `group2`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `db1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1 (Ranger ID: 9)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `db1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`db1` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `db1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1 (Ranger ID: 9)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `db1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user3@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`db1` TO `user3@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `db1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user3@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1 (Ranger ID: 9)
-- Type: GRANT | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `db1`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user4@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`db1` TO `user4@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `db1` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user4@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: url=http://qe-s3-bucket-mst/test_abcd/abcd/ URL-access-policy (Ranger ID: 201)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: http://qe-s3-bucket-mst/test_abcd/abcd/ (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_http___qe_s3_bucket_mst_test_abcd_abcd>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_http___qe_s3_bucket_mst_test_abcd_abcd>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=org; table=employee; column=* (Ranger ID: 1001)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`org`.`employee` TO `john@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
