-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 4 of 4
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: audit-all-access under /finance/restricted/ (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted/ (recursive)
-- ⚠ Ensure External Location `ext_loc_finance_restricted` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-all under /public/ (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/* (recursive)
-- ⚠ Ensure External Location `ext_loc_public__` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ FILES ON EXTERNAL LOCATION `ext_loc_public__` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /finance/restricted (Ranger ID: 3)
-- Type: HDFS_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted (recursive)
-- ⚠ Ensure External Location `ext_loc_finance_restricted` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ FILES ON EXTERNAL LOCATION `ext_loc_finance_restricted` TO `finance`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /finance/limited (Ranger ID: 4)
-- Type: HDFS_GRANT | Principal: stewards
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/limited (recursive)
-- ⚠ Ensure External Location `ext_loc_finance_limited` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ FILES ON EXTERNAL LOCATION `ext_loc_finance_limited` TO `stewards`;
