-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 7 of 7
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ GRANT/DENY CONFLICT: 1 principal(s) have both a GRANT
-- and a DENY on the same table. In UC (additive model), GRANTs are permanent —
-- there is no DENY mechanism. The deny advisory below has NO effect unless either:
--   (a) the GRANT is revoked, or
--   (b) column masks are applied to restrict what the principal can see.
--   Affected: public on default.testTable

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; allow select with mutual exclusion of col* only for user2, admin; deny for everyone else (Ranger ID: 1)
-- Type: GRANT (WILDCARD COLUMN 'col*') | Principals: user2, admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT — pattern 'col*' → SQL LIKE 'col%'
-- Permitted principals: user2@company.com, admin@company.com
-- UC has no column-level GRANT. Strategy: mask matching columns to NULL for non-permitted principals.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR col AS (
    SELECT column_name
    FROM `main`.information_schema.columns
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name     = 'testTable'
      AND column_name LIKE 'col%'
  ) DO
    EXECUTE IMMEDIATE 'CREATE OR REPLACE FUNCTION `main`.`default`.mask_testTable_col_restrict_' || col.column_name || '(val STRING) RETURNS STRING RETURN IF(NOT ((current_user() = ''user2@company.com'') OR (current_user() = ''admin@company.com'')), NULL, val)';
    EXECUTE IMMEDIATE 'ALTER TABLE `main`.`default`.`testTable` ALTER COLUMN `' || col.column_name || '` SET MASK `main`.`default`.mask_testTable_col_restrict_' || col.column_name;
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; allow select with mutual exclusion of col* only for user2, admin; deny for everyone else (Ranger ID: 1)
-- Type: DENY | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.testTable for public
-- Column scope of deny: col*
--
-- ⚠ MUTUAL EXCLUSION (accessed-together) CONDITION DETECTED
-- This deny only triggers when ALL of the following columns are queried
-- SIMULTANEOUSLY in a single query (column co-access prevention):
--   • default.testTable.col*
-- Unity Catalog has NO equivalent for query-level column co-access prevention.
-- Ranger uses this to stop correlation attacks (e.g. joining quasi-identifiers).
-- UC ALTERNATIVE: Apply a column mask on each sensitive column so that
-- non-exempt principals always see a masked/null value regardless of
-- which other columns are queried at the same time.
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • group: admin
--   • user: user2
--   • user: admin
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (public) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove public from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place
--
-- ✅ SUGGESTED DENY APPROXIMATION — column pattern 'col*' → SQL LIKE 'col%'
-- Denied principal: public (except: admin, user2, admin)
-- Strategy: mask columns matching the pattern to NULL for the denied principal.
-- ⚠ UC has no DENY — this is an additive mask approximation. Do NOT grant the
-- denied principal (public) SELECT on this table.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR col AS (
    SELECT column_name
    FROM `main`.information_schema.columns
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name     = 'testTable'
      AND column_name LIKE 'col%'
  ) DO
    EXECUTE IMMEDIATE 'CREATE OR REPLACE FUNCTION `main`.`default`.mask_testTable_deny_public_' || col.column_name || '(val STRING) RETURNS STRING RETURN IF((IS_ACCOUNT_GROUP_MEMBER(''public'') AND NOT ((IS_ACCOUNT_GROUP_MEMBER(''admin'')) OR (current_user() = ''user2@company.com'') OR (current_user() = ''admin@company.com''))), NULL, val)';
    EXECUTE IMMEDIATE 'ALTER TABLE `main`.`default`.`testTable` ALTER COLUMN `' || col.column_name || '` SET MASK `main`.`default`.mask_testTable_deny_public_' || col.column_name;
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; deny select with mutual exclusion of col1, name for everone except admin (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`testTable` TO `admin@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; deny select with mutual exclusion of col1, name for everone except admin (Ranger ID: 2)
-- Type: DENY | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.testTable for public
-- Column scope of deny: col1
--
-- ⚠ MUTUAL EXCLUSION (accessed-together) CONDITION DETECTED
-- This deny only triggers when ALL of the following columns are queried
-- SIMULTANEOUSLY in a single query (column co-access prevention):
--   • default.testTable.col1
--   • default.testTable.name
-- Unity Catalog has NO equivalent for query-level column co-access prevention.
-- Ranger uses this to stop correlation attacks (e.g. joining quasi-identifiers).
-- UC ALTERNATIVE: Apply a column mask on each sensitive column so that
-- non-exempt principals always see a masked/null value regardless of
-- which other columns are queried at the same time.
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: admin
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (public) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove public from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place
--
-- ✅ SUGGESTED COLUMN MASKS — UC approximation of the accessed-together deny:
-- Applies NULL masking on each affected column for 'public',
-- while exempting the denyException principals listed above.
-- ⚠ BEHAVIOR DIFFERENCE: In Ranger the deny fires only when ALL listed columns
-- are accessed SIMULTANEOUSLY. These masks restrict EACH column independently,
-- which is MORE restrictive. Verify this is acceptable before deploying.
-- Columns masked: col1, name

CREATE OR REPLACE FUNCTION `main`.`default`.mask_testTable_col1_deny_public(val STRING)
RETURNS STRING
RETURN IF((IS_ACCOUNT_GROUP_MEMBER('public') AND NOT (current_user() = 'admin@company.com')), NULL, val);

ALTER TABLE `main`.`default`.`testTable`
ALTER COLUMN col1 SET MASK `main`.`default`.mask_testTable_col1_deny_public;

CREATE OR REPLACE FUNCTION `main`.`default`.mask_testTable_name_deny_public(val STRING)
RETURNS STRING
RETURN IF((IS_ACCOUNT_GROUP_MEMBER('public') AND NOT (current_user() = 'admin@company.com')), NULL, val);

ALTER TABLE `main`.`default`.`testTable`
ALTER COLUMN name SET MASK `main`.`default`.mask_testTable_name_deny_public;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=testTable; column=*; allow access to everyone (Ranger ID: 3)
-- Type: SKIPPED_BLANK_PRINCIPAL | Principal: None
-- ═══════════════════════════════════════════════════════
-- ⚠ BLANK PRINCIPAL SKIPPED — NO GRANT GENERATED
-- Policy: db=default; table=testTable; column=*; allow access to everyone
-- Resource: `main`.`default`.`testTable`
-- Blank entries found: users[0] is empty
-- These entries were omitted because an empty user/group/role name
-- cannot be mapped to a Databricks principal.
-- ACTION REQUIRED: Open the Ranger policy, assign explicit principal names,
-- re-export the policy JSON, and re-run the migration.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=testTable; column=*; allow access to everyone (Ranger ID: 3)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`testTable` TO `public`;
