-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hdfs_zones
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: all - path (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: hadoop
-- ═══════════════════════════════════════════════════════
-- HDFS path: /* (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc__>` TO `hadoop@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc__>` TO `hadoop@company.com`;
-- Note: delegateAdmin=true. Consider granting MANAGE on the External Location.

-- ═══════════════════════════════════════════════════════
-- Policy: kms-audit-path (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: keyadmin
-- ═══════════════════════════════════════════════════════
-- HDFS path: /ranger/audit/kms (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_ranger_audit_kms>` TO `keyadmin@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_ranger_audit_kms>` TO `keyadmin@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: Finance for default zone (Ranger ID: 40)
-- Type: HDFS_GRANT | Principal: sales-admin
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_finance>` TO `sales-admin@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_finance>` TO `sales-admin@company.com`;
