-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 85 of 85
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ GRANT/DENY CONFLICT: 4 principal(s) have both a GRANT
-- and a DENY on the same table. In UC (additive model), GRANTs are permanent —
-- there is no DENY mechanism. The deny advisory below has NO effect unless either:
--   (a) the GRANT is revoked, or
--   (b) column masks are applied to restrict what the principal can see.
--   Affected: user2 on default.test2
--   Affected: user3 on default.test2
--   Affected: user2 on default.table
--   Affected: user3 on default.table

-- ═══════════════════════════════════════════════════════
-- Policy: db=default: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test1` TO `group1`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test1` TO `group2`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test1` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test1` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test2` TO `group1`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test2` TO `group2`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test2` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test2` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`test1` TO `cluster-admin`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`test1` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`test1` TO `admin@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`test1` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`test2` TO `cluster-admin`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`test2` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column1 (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`test2` TO `admin@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`test2` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for group1 on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for group2 on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user1 on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user2 on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for group1 on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for group2 on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user1 on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user2 on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for cluster-admin on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for admin on default.test1 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for cluster-admin on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test1,test2; column=column2 (Ranger ID: 3)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for admin on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=fin_*; column=* (Ranger ID: 4)
-- Type: GRANT | Principal: finance-controller
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fin_*  →  SQL LIKE: 'fin_%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE 'fin_%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`finance`.`' || tbl.table_name || '` TO `finance-controller`';
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=fin_*; column=* (Ranger ID: 4)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fin_*  →  SQL LIKE: 'fin_%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE 'fin_%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`finance`.`' || tbl.table_name || '` TO `user1@company.com`';
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=fin_*; column=* (Ranger ID: 4)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fin_*  →  SQL LIKE: 'fin_%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE 'fin_%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`finance`.`' || tbl.table_name || '` TO `user2@company.com`';
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tmp; column=tmp* (Ranger ID: 5)
-- Type: GRANT (WILDCARD COLUMN 'tmp*') | Principals: cluster-admin, finance-controller, user1, user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT — pattern 'tmp*' → SQL LIKE 'tmp%'
-- Permitted principals: cluster-admin, finance-controller, user1@company.com, user2@company.com
-- UC has no column-level GRANT. Strategy: mask matching columns to NULL for non-permitted principals.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR col AS (
    SELECT column_name
    FROM `main`.information_schema.columns
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name     = 'tmp'
      AND column_name LIKE 'tmp%'
  ) DO
    EXECUTE IMMEDIATE 'CREATE OR REPLACE FUNCTION `main`.`db1`.mask_tmp_col_restrict_' || col.column_name || '(val STRING) RETURNS STRING RETURN IF(NOT ((IS_ACCOUNT_GROUP_MEMBER(''cluster-admin'')) OR (IS_ACCOUNT_GROUP_MEMBER(''finance-controller'')) OR (current_user() = ''user1@company.com'') OR (current_user() = ''user2@company.com'')), NULL, val)';
    EXECUTE IMMEDIATE 'ALTER TABLE `main`.`db1`.`tmp` ALTER COLUMN `' || col.column_name || '` SET MASK `main`.`db1`.mask_tmp_col_restrict_' || col.column_name;
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr;udf=udf (Ranger ID: 6)
-- Type: UDF_GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.hr.udf is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`hr`.`udf` TO `cluster-admin`;
-- Note: delegateAdmin=true. Consider granting MANAGE on FUNCTION main.hr.udf.

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr;udf=udf (Ranger ID: 6)
-- Type: UDF_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.hr.udf is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`hr`.`udf` TO `user1@company.com`;
-- Note: delegateAdmin=true. Consider granting MANAGE on FUNCTION main.hr.udf.

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr;udf=udf (Ranger ID: 6)
-- Type: UDF_GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.hr.udf is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`hr`.`udf` TO `user2@company.com`;
-- Note: delegateAdmin=true. Consider granting MANAGE on FUNCTION main.hr.udf.

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr*;udf=udf (Ranger ID: 8)
-- Type: UDF_GRANT | Principal: hr-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.hr*.udf is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`hr*`.`udf` TO `hr-admin`;
-- Note: delegateAdmin=true. Consider granting MANAGE on FUNCTION main.hr*.udf.

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr*;udf=udf (Ranger ID: 8)
-- Type: UDF_GRANT | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.hr*.udf is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`hr*`.`udf` TO `user4@company.com`;
-- Note: delegateAdmin=true. Consider granting MANAGE on FUNCTION main.hr*.udf.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for user2 on default.test2 was already emitted above.
-- Original column scope: ['column2'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column2
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`test2` TO `user3@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: DENY | Principal: group3
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT, CREATE on main.default.test2 for group3
-- Column scope of deny: column2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user3
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (group3) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove group3 from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: DENY | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT, CREATE on main.default.test2 for user2@company.com
-- Column scope of deny: column2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user3
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (user2@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove user2@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: DENY | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT, CREATE on main.default.test2 for user3@company.com
-- Column scope of deny: column2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user3
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (user3@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove user3@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test2; column=column2 (Ranger ID: 9)
-- Type: DENY | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT, CREATE on main.default.test2 for user4@company.com
-- Column scope of deny: column2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user3
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (user4@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove user4@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=fin_*; column=salary (Ranger ID: 10)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fin_*  →  SQL LIKE: 'fin_%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE 'fin_%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`finance`.`' || tbl.table_name || '` TO `cluster-admin`';
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=fin_*; column=salary (Ranger ID: 10)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: fin_*  →  SQL LIKE: 'fin_%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'finance'
      AND table_name LIKE 'fin_%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`finance`.`' || tbl.table_name || '` TO `user3@company.com`';
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: GRANT | Principal: cluster-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`table` TO `cluster-admin`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`table` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user1@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`table` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user2@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`table` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user3@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`table` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: GRANT | Principal: user4
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user4@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`default`.`table` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: DENY | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.table for public
-- Column scope of deny: column
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user2
--   • user: user4
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (public) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove public from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: DENY | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.table for user2@company.com
-- Column scope of deny: column
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user2
--   • user: user4
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (user2@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove user2@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 11)
-- Type: DENY | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.table for user3@company.com
-- Column scope of deny: column
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: user2
--   • user: user4
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (user3@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove user3@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: GRANT | Principal: accounting
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): status
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `accounting`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `accounting`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`finance`.`accounts` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): status
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `admin`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `admin`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`finance`.`accounts` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): status
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `john@company.com`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `john@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`finance`.`accounts` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: GRANT | Principal: jane
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): status
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `jane@company.com`;
GRANT MODIFY ON TABLE `main`.`finance`.`accounts` TO `jane@company.com`;
-- Note: delegateAdmin=true in Ranger. Consider granting MANAGE on TABLE `main`.`finance`.`accounts` if admin delegation is needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): status
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`finance`.`accounts` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=status (Ranger ID: 12)
-- Type: DENY | Principal: housekeeping
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.finance.accounts for housekeeping
-- Column scope of deny: status
--
-- RECOMMENDED ACTIONS:
-- 1. Remove housekeeping from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: GRANT | Principal: accounting
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for accounting on finance.accounts was already emitted above.
-- Original column scope: ['amount'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for admin on finance.accounts was already emitted above.
-- Original column scope: ['amount'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for john on finance.accounts was already emitted above.
-- Original column scope: ['amount'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: GRANT | Principal: jane
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for jane on finance.accounts was already emitted above.
-- Original column scope: ['amount'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for public on finance.accounts was already emitted above.
-- Original column scope: ['amount'] (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=finance; table=accounts; column=amount (Ranger ID: 13)
-- Type: DENY | Principal: housekeeping
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.finance.accounts for housekeeping
-- Column scope of deny: amount
--
-- RECOMMENDED ACTIONS:
-- 1. Remove housekeeping from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl1; column=col1 (Ranger ID: 13)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db1`.`tbl1` TO `john@company.com`;
GRANT MODIFY ON TABLE `main`.`db1`.`tbl1` TO `john@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl1; column=col1 (Ranger ID: 13)
-- Type: GRANT | Principal: jane
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db1`.`tbl1` TO `jane@company.com`;
GRANT MODIFY ON TABLE `main`.`db1`.`tbl1` TO `jane@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl1; column=col1 (Ranger ID: 13)
-- Type: DENY | Principal: adam
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db1.tbl1 for adam@company.com
-- Column scope of deny: col1
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: eve
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (adam@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove adam@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl1; column=col1 (Ranger ID: 13)
-- Type: DENY | Principal: eve
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db1.tbl1 for eve@company.com
-- Column scope of deny: col1
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: eve
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (eve@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove eve@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db2; table=tbl2; column=col2 (Ranger ID: 14)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col2
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db2`.`tbl2` TO `john@company.com`;
GRANT MODIFY ON TABLE `main`.`db2`.`tbl2` TO `john@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db2; table=tbl2; column=col2 (Ranger ID: 14)
-- Type: GRANT | Principal: jane
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col2
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db2`.`tbl2` TO `jane@company.com`;
GRANT MODIFY ON TABLE `main`.`db2`.`tbl2` TO `jane@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db2; table=tbl2; column=col2 (Ranger ID: 14)
-- Type: DENY | Principal: adam
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db2.tbl2 for adam@company.com
-- Column scope of deny: col2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: eve
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (adam@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove adam@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db2; table=tbl2; column=col2 (Ranger ID: 14)
-- Type: DENY | Principal: eve
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db2.tbl2 for eve@company.com
-- Column scope of deny: col2
--
-- DENY EXCEPTIONS (these principals are exempt from this deny):
--   • user: eve
-- These principals retain access even though the deny applies to the group above.
-- In UC (additive model), simply grant them explicitly and do not grant the
-- denied group (eve@company.com) at all — or apply column masks only for that group.
--
-- RECOMMENDED ACTIONS:
-- 1. Remove eve@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: GRANT | Principal: john
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col3
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db3`.`tbl3` TO `john@company.com`;
GRANT MODIFY ON TABLE `main`.`db3`.`tbl3` TO `john@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: GRANT | Principal: jane
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col3
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db3`.`tbl3` TO `jane@company.com`;
GRANT MODIFY ON TABLE `main`.`db3`.`tbl3` TO `jane@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: GRANT | Principal: tarzan
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): col3
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`db3`.`tbl3` TO `tarzan`;
GRANT MODIFY ON TABLE `main`.`db3`.`tbl3` TO `tarzan`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: DENY | Principal: adam
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db3.tbl3 for adam@company.com
-- Column scope of deny: col3
--
-- RECOMMENDED ACTIONS:
-- 1. Remove adam@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: DENY | Principal: eve
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db3.tbl3 for eve@company.com
-- Column scope of deny: col3
--
-- RECOMMENDED ACTIONS:
-- 1. Remove eve@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=db3; table=tbl3; column=col3 (Ranger ID: 15)
-- Type: DENY | Principal: eden
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: DROP on main.db3.tbl3 for eden
-- Column scope of deny: col3
--
-- RECOMMENDED ACTIONS:
-- 1. Remove eden from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=denyAllElse; table=table-1; column=column-1 (Ranger ID: 20)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column-1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`denyAllElse`.`table-1` TO `user1@company.com`;
GRANT MODIFY ON TABLE `main`.`denyAllElse`.`table-1` TO `user1@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`denyAllElse`.`table-1` TO `user1@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON TABLE `main`.`denyAllElse`.`table-1` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=denyAllElse; table=table-1; column=column-1 (Ranger ID: 20)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column-1
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
GRANT SELECT ON TABLE `main`.`denyAllElse`.`table-1` TO `user3@company.com`;
GRANT MODIFY ON TABLE `main`.`denyAllElse`.`table-1` TO `user3@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`denyAllElse`.`table-1` TO `user3@company.com`;
-- ⚠ ALTER privilege has no direct equivalent in Unity Catalog. Converted to ALL PRIVILEGES (closest available substitute for DDL access). In UC, table/schema structural changes (ADD COLUMN, RENAME, etc.) require ownership. Review: consider assigning object ownership instead of granting ALL PRIVILEGES.
GRANT ALL PRIVILEGES ON TABLE `main`.`denyAllElse`.`table-1` TO `user3@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=user_{USER }, table=*, column=* (Ranger ID: 21)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard schema pattern: user_{USER }*  →  SQL LIKE: 'user_{USER }%'
-- UC does not support wildcards in GRANT ON SCHEMA.
-- The block below loops through all matching schemas and applies the grant.
-- SELECT and MODIFY are table-level privileges — a nested per-table loop
-- follows the schema loop to apply them to every table in each matched schema.
-- ⚠ Tables added after this script runs will NOT inherit these grants.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR sch AS (
    SELECT schema_name
    FROM `main`.information_schema.schemata
    WHERE catalog_name = 'main'
      AND schema_name LIKE 'user_{USER }%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT USE CATALOG ON CATALOG `main` TO `public`';
    EXECUTE IMMEDIATE 'GRANT USE SCHEMA ON SCHEMA `main`.`' || sch.schema_name || '` TO `public`';
  END FOR;
END;
-- ⚠ SELECT: table-level privilege — applied per-table below for schemas LIKE 'user_{USER }%'.
BEGIN
  FOR tbl AS (
    SELECT table_schema, table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema LIKE 'user_{USER }%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`' || tbl.table_schema || '`.`' || tbl.table_name || '` TO `public`';
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — applied per-table below for schemas LIKE 'user_{USER }%'.
BEGIN
  FOR tbl AS (
    SELECT table_schema, table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema LIKE 'user_{USER }%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`' || tbl.table_schema || '`.`' || tbl.table_name || '` TO `public`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=dept_${{USER.dept}}, table=*, column=* (Ranger ID: 22)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ RESOURCE NOT TRANSLATED — Ranger request-context attribute in resource name
-- Policy: db=dept_${{USER.dept}}, table=*, column=*
-- Affected resource component(s): `dept_${{USER.dept}}`
-- Principal: public
--
-- Ranger supports dynamic resource names like dept_${{USER.dept}} where the
-- table name is resolved per-user at query time. Unity Catalog requires
-- fixed, pre-known resource names — dynamic resource names are not supported.
--
-- ACTION REQUIRED: Identify all concrete table names this policy covers,
-- then create one GRANT statement per table for each applicable principal.

-- ═══════════════════════════════════════════════════════
-- Policy: db=dept_${{USER.dept}}, table=*, column=* (Ranger ID: 22)
-- Type: GRANT | Principal: engg
-- ═══════════════════════════════════════════════════════
-- ⛔ RESOURCE NOT TRANSLATED — Ranger request-context attribute in resource name
-- Policy: db=dept_${{USER.dept}}, table=*, column=*
-- Affected resource component(s): `dept_${{USER.dept}}`
-- Principal: engg
--
-- Ranger supports dynamic resource names like dept_${{USER.dept}} where the
-- table name is resolved per-user at query time. Unity Catalog requires
-- fixed, pre-known resource names — dynamic resource names are not supported.
--
-- ACTION REQUIRED: Identify all concrete table names this policy covers,
-- then create one GRANT statement per table for each applicable principal.

-- ═══════════════════════════════════════════════════════
-- Policy: db=dept_engg, table=*, column=* (Ranger ID: 23)
-- Type: GRANT | Principal: engg
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `dept_engg`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `engg`;
GRANT USE SCHEMA ON SCHEMA `main`.`dept_engg` TO `engg`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `dept_engg` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'dept_engg'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`dept_engg`.`' || tbl.table_name || '` TO `engg`';
  END FOR;
END;
