-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 5 of 5
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ NESTED PATH NOTICE: 2 HDFS/URL path pair(s) have a parent→child relationship.
-- All HDFS paths are mapped to External Volumes under a single parent
-- External Location. Volumes are in `main`.`ranger_hdfs_volumes`.
-- Sub-path volumes are GRANT-able independently — no overlapping location conflict.
--   Parent path: /public  →  Child volume: /public/finance
--   Parent path: /public/*  →  Child volume: /public/finance

-- ═══════════════════════════════════════════════════════
-- Policy: audit-all-access under /public (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).

-- ═══════════════════════════════════════════════════════
-- Policy: allow-execute-to-all under /public/ (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/* (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public__` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_public__` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /public/finance (Ranger ID: 3)
-- Type: HDFS_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` TO `finance@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /public/finance to user guest (Ranger ID: 5)
-- Type: HDFS_GRANT | Principal: guest
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` TO `guest@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-execute-to-finance under /public/finance to user guest (Ranger ID: 6)
-- Type: HDFS_GRANT | Principal: guest
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_public_finance` TO `guest@company.com`;
