-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hbase_multiple_matching_policies
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 6 of 6
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: table=default,*; column-family=default,*; column=default, *: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HBase column-families (default, *) have no direct UC equivalent — table-level grant applied.
GRANT SELECT ON TABLE `main`.`default`.`default` TO `user1@company.com`;
GRANT MODIFY ON TABLE `main`.`default`.`default` TO `user1@company.com`;
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`default` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: table=default,*; column-family=default,*; column=default, *: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.

-- ═══════════════════════════════════════════════════════
-- Policy: table=default,*; column-family=default,*; column=default, *: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: hrt_qa
-- ═══════════════════════════════════════════════════════
-- HBase column-families (default, *) have no direct UC equivalent — table-level grant applied.
GRANT SELECT ON TABLE `main`.`default`.`default` TO `hrt_qa@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: table=default,*; column-family=default,*; column=default, *: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: hrt_qa
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.

-- ═══════════════════════════════════════════════════════
-- Policy: table=*; column-family=*; column=*: audit-all-access (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.

-- ═══════════════════════════════════════════════════════
-- Policy: table=*; column-family=*; column=*: audit-all-access (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: hrt_qa
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.
