-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_aclprovider_hdfs
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 4 of 4
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: audit-all-access under /finance/restricted/ (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted/ (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-all under /public/ (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/* (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_public__>` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /finance/restricted (Ranger ID: 3)
-- Type: HDFS_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_finance_restricted>` TO `finance`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /finance/limited (Ranger ID: 4)
-- Type: HDFS_GRANT | Principal: stewards
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/limited (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_finance_limited>` TO `stewards`;
