-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 6 of 6
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=default: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default (Ranger ID: 2)
-- Type: GRANT | Principal: role-group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `role-group1`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `role-group1`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `role-group1`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`default` TO `role-group1`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `default` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `role-group1`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `default` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `user1@company.com`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default (Ranger ID: 2)
-- Type: GRANT | Principal: fin-admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `fin-admin`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `fin-admin`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `fin-admin`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`default` TO `fin-admin`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `default` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fin-admin`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default (Ranger ID: 2)
-- Type: GRANT | Principal: fin-group
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `fin-group`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `fin-group`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `fin-group`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`default` TO `fin-group`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `default` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`default`.`' || tbl.table_name || '` TO `fin-group`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=hr-fin (Ranger ID: 3)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `hr-fin`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`hr-fin` TO `public`;
GRANT CREATE TABLE ON SCHEMA `main`.`hr-fin` TO `public`;
