-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 8 of 8
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `hive@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user2@company.com`;
