-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hive_incremental_delete
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 15 of 15
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=default: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- UC schema-level grant applies to all current AND future tables in this schema — broader scope than the original Ranger policy.
-- Review: consider explicit per-table grants for sensitive schemas.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: test*  →  SQL LIKE: 'test%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE 'test%'
  ) DO
    -- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
    -- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
    EXECUTE IMMEDIATE format('GRANT MANAGE ON TABLE `main`.`default`.`%s` TO `admin`', tbl.table_name);
  END FOR;
END;
-- Note: delegateAdmin=true. Consider MANAGE on each matched table if delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=test*; column=* (Ranger ID: 2)
-- Type: GRANT | Principal: admin
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for admin on default.test* was already emitted above.
-- Original column scope: * (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group1`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: group2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `group2`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tbl*; column=* (Ranger ID: 3)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger wildcard table pattern: tbl*  →  SQL LIKE: 'tbl%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name LIKE 'tbl%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`db1`.`%s` TO `user2@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=db1; table=tmp; column=tmp* (Ranger ID: 4)
-- Type: GRANT (WILDCARD COLUMN 'tmp*') | Principals: group1, group2, user1, user2
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT — pattern 'tmp*' → SQL LIKE 'tmp%'
-- Permitted principals: group1, group2, user1@company.com, user2@company.com
-- UC has no column-level GRANT. Strategy: mask matching columns to NULL for non-permitted principals.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR col AS (
    SELECT column_name
    FROM `main`.information_schema.columns
    WHERE table_catalog = 'main'
      AND table_schema   = 'db1'
      AND table_name     = 'tmp'
      AND column_name LIKE 'tmp%'
  ) DO
    EXECUTE IMMEDIATE format(
      'CREATE OR REPLACE FUNCTION `main`.`db1`.mask_tmp_col_restrict_%s(val STRING) RETURNS STRING RETURN IF(NOT ((IS_ACCOUNT_GROUP_MEMBER(''group1'')) OR (IS_ACCOUNT_GROUP_MEMBER(''group2'')) OR (current_user() = ''user1@company.com'') OR (current_user() = ''user2@company.com'')), NULL, val)',
      col.column_name
    );
    EXECUTE IMMEDIATE format(
      'ALTER TABLE `main`.`db1`.`tmp` ALTER COLUMN `%s` SET MASK `main`.`db1`.mask_tmp_col_restrict_%s',
      col.column_name, col.column_name
    );
  END FOR;
END;
