-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: cl1_hadoop
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: all - path (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: hadoop
-- ═══════════════════════════════════════════════════════
-- HDFS path: /* (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc__` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc__` TO `hadoop@company.com`;
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc__` TO `hadoop@company.com`;
-- Note: delegateAdmin=true. Consider granting MANAGE on the Volume.

-- ═══════════════════════════════════════════════════════
-- Policy: kms-audit-path (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: keyadmin
-- ═══════════════════════════════════════════════════════
-- HDFS path: /ranger/audit/kms (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_ranger_audit_kms` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_ranger_audit_kms` TO `keyadmin@company.com`;
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_ranger_audit_kms` TO `keyadmin@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: Finance for default zone (Ranger ID: 40)
-- Type: HDFS_GRANT | Principal: sales-admin
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_finance` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_finance` TO `sales-admin@company.com`;
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_finance` TO `sales-admin@company.com`;
