-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: read to mybu-analyst (Ranger ID: 162)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/analyst (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_analyst` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_analyst` TO `superman@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: write to mybu-admin (Ranger ID: 163)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/analyst (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_analyst` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_analyst` TO `superman@company.com`;
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_analyst` TO `superman@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: write to mybu-admin (Ranger ID: 163)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/admin (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_admin` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_admin` TO `superman@company.com`;
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_mybu_admin` TO `superman@company.com`;
