-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 5 of 5
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: database=*,table=*,column=* - audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: database=* - allow anyone to create database; grant owner all access  (Ranger ID: 2)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
-- GRANT CREATE ON CATALOG — not valid in UC; grant on individual schemas or tables instead.

-- ═══════════════════════════════════════════════════════
-- Policy: database=* - allow anyone to create database; grant owner all access  (Ranger ID: 2)
-- Type: GRANT | Principal: {OWNER}
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `{OWNER}@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `{OWNER}@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: database=*,table=* - allow owner all access to table (Ranger ID: 3)
-- Type: GRANT | Principal: {OWNER}
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for {OWNER} on *.None was already emitted above.
-- Original column scope: * (widened to table-level in UC).

-- ═══════════════════════════════════════════════════════
-- Policy: database=*;table=*;column=* - allow owner all access to column (Ranger ID: 4)
-- Type: GRANT | Principal: {OWNER}
-- ═══════════════════════════════════════════════════════
-- ℹ DUPLICATE GRANT SKIPPED — identical GRANT for {OWNER} on *.None was already emitted above.
-- Original column scope: * (widened to table-level in UC).
