-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hbase
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 4 of 4
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: table=finance; column-family=restricted*: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HBase column-families (restricted*) have no direct UC equivalent — table-level grant applied.

-- ═══════════════════════════════════════════════════════
-- Policy: table=finance; column-family=restricted* (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HBase column-families (restricted*) have no direct UC equivalent — table-level grant applied.
GRANT SELECT ON TABLE `main`.`default`.`finance` TO `finance`;
GRANT MODIFY ON TABLE `main`.`default`.`finance` TO `finance`;

-- ═══════════════════════════════════════════════════════
-- Policy: table=finance; column-family=restricted* (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: finance-admin
-- ═══════════════════════════════════════════════════════
-- HBase column-families (restricted*) have no direct UC equivalent — table-level grant applied.
GRANT ALL PRIVILEGES ON TABLE `main`.`default`.`finance` TO `finance-admin`;
-- Note: delegateAdmin=true. Consider MANAGE on TABLE `main`.`default`.`finance` if admin delegation needed.

-- ═══════════════════════════════════════════════════════
-- Policy: table=*; column-family=<excluding>restricted* (Ranger ID: 3)
-- Type: HBASE_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.
