-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_aclprovider_mask_filter
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 22 of 22
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 7 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `employee`.`personal` have been combined into one function.
-- Principals merged (2): user1@company.com, user2@company.com
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`employee`.rf_personal(location STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN location='US'
    WHEN current_user() = 'user2@company.com' THEN location='CA'
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
SET ROW FILTER `main`.`employee`.rf_personal ON (location);

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `hr`.`employee` have been combined into one function.
-- Principals merged (3): user1@company.com, user2@company.com, user3@company.com
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`hr`.rf_employee(dept STRING, location STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN dept='production'
    WHEN current_user() = 'user2@company.com' THEN dept='purchase'
    WHEN current_user() = 'user3@company.com' THEN location='GR'
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`hr`.`employee`
SET ROW FILTER `main`.`hr`.rf_employee ON (dept, location);

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `hr`.`employee2` have been combined into one function.
-- Principals merged (2): user1@company.com, user2@company.com
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`hr`.rf_employee2(dept STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN dept='production'
    WHEN current_user() = 'user2@company.com' THEN dept='purchase'
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`hr`.`employee2`
SET ROW FILTER `main`.`hr`.rf_employee2 ON (dept);

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `employee`.`personal`.ssn have been combined.
-- Principals merged (4): user1@company.com, user2@company.com, user1@company.com, user2@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_ssn(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN ssn SET MASK `main`.`employee`.mask_personal_ssn;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `employee`.`personal`.dummy have been combined.
-- Principals merged (2): user1@company.com, user2@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_dummy(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN dummy SET MASK `main`.`employee`.mask_personal_dummy;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `hr`.`employee`.date_of_birth have been combined.
-- Principals merged (3): user1@company.com, user2@company.com, user3@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`hr`.mask_employee_date_of_birth(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user3@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`hr`.`employee`
ALTER COLUMN date_of_birth SET MASK `main`.`hr`.mask_employee_date_of_birth;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `hr`.`employee`.project have been combined.
-- Principals merged (2): user1@company.com, user2@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`hr`.mask_employee_project(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`hr`.`employee`
ALTER COLUMN project SET MASK `main`.`hr`.mask_employee_project;

-- ═══════════════════════════════════════════════════════
-- Policy: db=test_db, table=dept_${{USER.dept}}, column=col1: unmasked for users in the department (Ranger ID: 104)
-- Type: COLUMN_MASK | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ RESOURCE NOT TRANSLATED — Ranger request-context attribute in resource name
-- Policy: db=test_db, table=dept_${{USER.dept}}, column=col1: unmasked for users in the department
-- Affected resource component(s): `dept_${{USER.dept}}`
-- Principal: {USER}@company.com
--
-- Ranger supports dynamic resource names like dept_${{USER.dept}} where the
-- table name is resolved per-user at query time. Unity Catalog requires
-- fixed, pre-known resource names — dynamic resource names are not supported.
--
-- ACTION REQUIRED: Identify all concrete table names this policy covers,
-- then create one GRANT statement per table for each applicable principal.

-- ═══════════════════════════════════════════════════════
-- Policy: db=test_db, table=dept_hr, column=col1: mask hash for all users (Ranger ID: 105)
-- Type: COLUMN_MASK | Principal: public
-- ═══════════════════════════════════════════════════════
-- Column Mask: SHA-256 hash for public
CREATE OR REPLACE FUNCTION `main`.`test_db`.mask_dept_hr_col1_public(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('public'),
  SHA2(val, 256),
  val
);

ALTER TABLE `main`.`test_db`.`dept_hr`
ALTER COLUMN col1 SET MASK `main`.`test_db`.mask_dept_hr_col1_public;

-- ═══════════════════════════════════════════════════════
-- Policy: db=test_db, table=dept_${{USER.dept}}: no filter for users in the department (Ranger ID: 204)
-- Type: ROW_FILTER | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ RESOURCE NOT TRANSLATED — Ranger request-context attribute in resource name
-- Policy: db=test_db, table=dept_${{USER.dept}}: no filter for users in the department
-- Affected resource component(s): `dept_${{USER.dept}}`
-- Principal: {USER}@company.com
--
-- Ranger supports dynamic resource names like dept_${{USER.dept}} where the
-- table name is resolved per-user at query time. Unity Catalog requires
-- fixed, pre-known resource names — dynamic resource names are not supported.
--
-- ACTION REQUIRED: Identify all concrete table names this policy covers,
-- then create one GRANT statement per table for each applicable principal.

-- ═══════════════════════════════════════════════════════
-- Policy: db=test_db, table=dept_hr: row-filter (Ranger ID: 205)
-- Type: ROW_FILTER | Principal: public
-- ═══════════════════════════════════════════════════════
-- Row Filter for: public
-- Original expression: dept != 'hr'

CREATE OR REPLACE FUNCTION `main`.`test_db`.rf_dept_hr_public(dept STRING)
RETURNS BOOLEAN
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('public'),
  dept != 'hr',
  TRUE  -- Allow access for principals not matching the condition
);

ALTER TABLE `main`.`test_db`.`dept_hr`
SET ROW FILTER `main`.`test_db`.rf_dept_hr_public ON (dept);
