-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: read to mybu-analyst (Ranger ID: 162)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/analyst (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_mybu_analyst>` TO `superman@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: write to mybu-admin (Ranger ID: 163)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/analyst (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_mybu_analyst>` TO `superman@company.com`;
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_mybu_analyst>` TO `superman@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: write to mybu-admin (Ranger ID: 163)
-- Type: HDFS_GRANT | Principal: superman
-- ═══════════════════════════════════════════════════════
-- HDFS path: /mybu/admin (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_mybu_admin>` TO `superman@company.com`;
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_mybu_admin>` TO `superman@company.com`;
