-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 10 of 10
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `hive@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default, table=table2: audit-all-access (Ranger ID: 103)
-- Type: DENY | Principal: denieduser
-- ═══════════════════════════════════════════════════════
-- ⛔ DENY NOT SUPPORTED IN UNITY CATALOG
-- Original Ranger deny: SELECT on main.default.table2 for denieduser@company.com
--
-- RECOMMENDED ACTIONS:
-- 1. Remove denieduser@company.com from the group that grants broad access
-- 2. Create a restricted schema and grant only specific tables
-- 3. Use row filters / column masks for fine-grained control
-- 4. If this was a safety-net deny, the UC additive model makes it unnecessary
--    as long as you don't grant the denied privileges in the first place

-- ═══════════════════════════════════════════════════════
-- Policy: db=default, table=table-override: audit-all-access (Ranger ID: 104)
-- Type: GRANT | Principal: user-override
-- ═══════════════════════════════════════════════════════
GRANT SELECT ON TABLE `main`.`default`.`table-override` TO `user-override@company.com`;
