-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hdfs_multiple_accesses
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 5 of 5
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: audit-all-access under /public (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.

-- ═══════════════════════════════════════════════════════
-- Policy: allow-execute-to-all under /public/ (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/* (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_public__>` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /public/finance (Ranger ID: 3)
-- Type: HDFS_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_public_finance>` TO `finance@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /public/finance to user guest (Ranger ID: 5)
-- Type: HDFS_GRANT | Principal: guest
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_public_finance>` TO `guest@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-execute-to-finance under /public/finance to user guest (Ranger ID: 6)
-- Type: HDFS_GRANT | Principal: guest
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/finance (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_public_finance>` TO `guest@company.com`;
