-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hbasedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 0 of 0
-- ╚═══════════════════════════════════════════════════════════╝

