-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hdfs_incremental_update
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 2 of 2
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-user1 /a/b* (Ranger ID: 10)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /a/b*
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_a_b_>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_a_b_>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-user1 /a/bc* (Ranger ID: 20)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /a/bc*
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_a_bc_>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_a_bc_>` TO `user1@company.com`;
