-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 2 of 2
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-user1 /a/b* (Ranger ID: 10)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /a/b*
-- ⚠ Ensure External Location `ext_loc_a_b_` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ FILES ON EXTERNAL LOCATION `ext_loc_a_b_` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `ext_loc_a_b_` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-user1 /a/bc* (Ranger ID: 20)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /a/bc*
-- ⚠ Ensure External Location `ext_loc_a_bc_` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ FILES ON EXTERNAL LOCATION `ext_loc_a_bc_` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `ext_loc_a_bc_` TO `user1@company.com`;
