-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: audit-all-access under /finance/restricted/ (Ranger ID: 1)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted/ (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_finance_restricted` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-all under /public/ (Ranger ID: 2)
-- Type: HDFS_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- HDFS path: /public/* (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_public__` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_public__` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-finance under /finance/restricted (Ranger ID: 3)
-- Type: HDFS_GRANT | Principal: finance
-- ═══════════════════════════════════════════════════════
-- HDFS path: /finance/restricted (recursive)
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_finance_restricted` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_finance_restricted` TO `finance`;
