-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hive_mask_filter_with_req_expressions
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 6 of 6
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `hive@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=employee, table=personal, column=ssn: mask ssn column (Ranger ID: 101)
-- Type: COLUMN_MASK | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ COLUMN MASK NOT TRANSLATED — Ranger-specific constructs detected
-- Policy:    db=employee, table=personal, column=ssn: mask ssn column
-- Column:    ssn
-- Principal: public
-- Original expression: CASE WHEN dept = '${{USER.dept}}' THEN {col} ELSE mask_show_last_n({col}, 4, 'x', 'x', 'x', -1, '1') END
--
-- The expression contains constructs that have no Unity Catalog equivalent:
--   • Request-context attribute(s) ${{USER.dept}}: Ranger substitutes these at query time from the user's identity attributes.
--   • Unity Catalog has no equivalent mechanism.
--   • Replace with IS_ACCOUNT_GROUP_MEMBER() checks or a lookup table join..
--   • {col}: Ranger column placeholder — not valid SQL.
--   • Replace with 'val' (the UC mask function parameter) or the literal column name..
--   • Ranger/Hive built-in mask function(s): mask_show_last_n().
--   • These are Hive UDFs not registered in Unity Catalog.
--   • Rewrite using UC-native expressions (CONCAT, LEFT, RIGHT, SHA2, etc.)..
--
-- ACTION REQUIRED: Rewrite this mask expression manually using UC-native expressions.
-- Common patterns:
--   • {col} → replace with 'val' (the UC mask function parameter).
--   • ${{USER.attr}} → use IS_ACCOUNT_GROUP_MEMBER() or a lookup table on current_user().
--   • Ranger mask UDFs → replace with CONCAT, LEFT, RIGHT, SHA2, etc.
-- Target function: `main`.`employee`.mask_personal_ssn_public
--
-- ✅ SUGGESTED SAFE-FALLBACK SQL (conservative — applies masking to all users):
-- The WHEN condition requiring request-context (${{USER.attr}}) has been dropped.
-- This is MORE restrictive than the original: no user receives the unmasked value
-- via the exemption condition. Verify this is acceptable before deploying.
-- Ranger UDF calls are approximated with UC-native string functions.
--
CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_ssn_public(val STRING)
RETURNS STRING
RETURN IF(
  IS_ACCOUNT_GROUP_MEMBER('public'),
  CONCAT(REPEAT('x', GREATEST(0, LENGTH(val) - 4)), RIGHT(val, 4)),
  val
);

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN ssn SET MASK `main`.`employee`.mask_personal_ssn_public;

-- ═══════════════════════════════════════════════════════
-- Policy: db=employee, table=personal (Ranger ID: 201)
-- Type: ROW_FILTER | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⛔ ROW FILTER NOT TRANSLATED — Ranger-specific constructs detected
-- Policy:    db=employee, table=personal
-- Principal: public
-- Original expression: dept='${{USER.dept}}'
--
-- The expression contains constructs that have no Unity Catalog equivalent:
--   • Request-context attribute(s) ${{USER.dept}}: Ranger substitutes these at query time from the user's identity attributes.
--   • Unity Catalog has no equivalent mechanism.
--   • Replace with IS_ACCOUNT_GROUP_MEMBER() checks or a lookup table join..
--
-- ACTION REQUIRED: Rewrite this row filter manually using UC-native expressions.
-- Common patterns:
--   • Attribute-based: use IS_ACCOUNT_GROUP_MEMBER() for group membership,
--     or join an attribute lookup table on current_user().
--   • {col} → replace with the column name or the 'val' parameter.
--   • Ranger mask UDFs → replace with CONCAT, LEFT, RIGHT, SHA2, etc.
-- Target function: `main`.`employee`.rf_personal_public
