-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hbasedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 3 of 3
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: table=*; column-family=*; column=*: audit-all-access (Ranger ID: 1)
-- Type: HBASE_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard (*) spans all namespaces — cannot be automatically translated.
-- Grant on specific schemas under catalog main manually.

-- ═══════════════════════════════════════════════════════
-- Policy: table=namespace_1:*; column-family=*; column=*: audit-all-access (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard namespace:* — grant on schema `namespace_1` covers all current AND future tables, broader than the original HBase namespace policy.
-- SELECT and MODIFY are table-level privileges in UC — applied via loop below.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`namespace_1` TO `user1@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`namespace_1` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON SCHEMA `main`.`namespace_1` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- ⚠ Tables added to `namespace_1` AFTER this script runs will NOT inherit this grant.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'namespace_1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE `main`.`namespace_1`.`' || tbl.table_name || '` TO `user1@company.com`';
  END FOR;
END;
-- ⚠ MODIFY: table-level privilege — granted per-table via loop below.
-- ⚠ Tables added to `namespace_1` AFTER this script runs will NOT inherit this grant.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'namespace_1'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE 'GRANT MODIFY ON TABLE `main`.`namespace_1`.`' || tbl.table_name || '` TO `user1@company.com`';
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: table=namespace_1:*; column-family=*; column=*: audit-all-access (Ranger ID: 2)
-- Type: HBASE_GRANT | Principal: hrt_qa
-- ═══════════════════════════════════════════════════════
-- ⚠ HBase wildcard namespace:* — grant on schema `namespace_1` covers all current AND future tables, broader than the original HBase namespace policy.
-- SELECT and MODIFY are table-level privileges in UC — applied via loop below.
GRANT USE CATALOG ON CATALOG `main` TO `hrt_qa@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`namespace_1` TO `hrt_qa@company.com`;
GRANT ALL PRIVILEGES ON SCHEMA `main`.`namespace_1` TO `hrt_qa@company.com`;
