-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hdfsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 1 of 1
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: user1_/test?_notrecursive (Ranger ID: 10)
-- Type: HDFS_GRANT | Principal: hrt_21
-- ═══════════════════════════════════════════════════════
-- HDFS path: /test?
-- ⚠ Ensure External Volume `main`.`ranger_hdfs_volumes`.`ext_loc_test_` exists before executing
--   (see _bootstrap_prerequisites.sql — STEP 5).
GRANT READ VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_test_` TO `hrt_21@company.com`;
GRANT WRITE VOLUME ON VOLUME `main`.`ranger_hdfs_volumes`.`ext_loc_test_` TO `hrt_21@company.com`;
