-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hive_mask_filter
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 12 of 12
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 4 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `employee`.`personal` have been combined into one function.
-- Principals merged (2): user1@company.com, user2@company.com
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`employee`.rf_personal(location STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN location='US'
    WHEN current_user() = 'user2@company.com' THEN location='CA'
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
SET ROW FILTER `main`.`employee`.rf_personal ON (location);

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED ROW FILTER — Unity Catalog supports only ONE row filter per table.
-- Multiple Ranger principals for `hr`.`employee` have been combined into one function.
-- Principals merged (2): user1@company.com, user2@company.com
-- Each WHEN clause applies the original Ranger filter for that principal.

CREATE OR REPLACE FUNCTION `main`.`hr`.rf_employee(dept STRING)
RETURNS BOOLEAN
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN dept='production'
    WHEN current_user() = 'user2@company.com' THEN dept='purchase'
    ELSE TRUE  -- allow access for all other principals
  END;

ALTER TABLE `main`.`hr`.`employee`
SET ROW FILTER `main`.`hr`.rf_employee ON (dept);

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `employee`.`personal`.ssn have been combined.
-- Principals merged (2): user1@company.com, user2@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_ssn(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN ssn SET MASK `main`.`employee`.mask_personal_ssn;

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `hr`.`employee`.date_of_birth have been combined.
-- Principals merged (2): user1@company.com, user2@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`hr`.mask_employee_date_of_birth(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user2@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`hr`.`employee`
ALTER COLUMN date_of_birth SET MASK `main`.`hr`.mask_employee_date_of_birth;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `hive@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user2@company.com`;
