-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hdfs_incremental_delete
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 1 of 1
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: user1_/test?_notrecursive (Ranger ID: 10)
-- Type: HDFS_GRANT | Principal: hrt_21
-- ═══════════════════════════════════════════════════════
-- HDFS path: /test?
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_test_>` TO `hrt_21@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_test_>` TO `hrt_21@company.com`;
