-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: test_policyengine_hive_with_partial_resource_policies
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 4 of 4
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: db=default: audit-all-access (Ranger ID: 1)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default (Ranger ID: 2)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (CREATE, DROP) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `user1@company.com`;
GRANT CREATE TABLE ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON SCHEMA `main`.`default` TO `user1@company.com`;
-- ⚠ SELECT: table-level privilege — granted per-table via loop below.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
-- ⚠ Tables added to `default` AFTER this script runs will NOT inherit this grant.
-- Re-run the relevant GRANT or add explicit per-table grants for new tables.
-- ⚠ Ranger wildcard table pattern: *  →  SQL LIKE: '%'
-- UC does not support wildcards in GRANT statements.
-- The block below loops through all matching tables at runtime and applies the grant.
-- Requires Databricks Runtime 14.0+ or a SQL Warehouse with scripting enabled.
BEGIN
  FOR tbl AS (
    SELECT table_name
    FROM `main`.information_schema.tables
    WHERE table_catalog = 'main'
      AND table_schema   = 'default'
      AND table_name LIKE '%'
  ) DO
    EXECUTE IMMEDIATE format('GRANT SELECT ON TABLE `main`.`default`.`%s` TO `user1@company.com`', tbl.table_name);
  END FOR;
END;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table (Ranger ID: 3)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`table` TO `user2@company.com`;
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=default; table=table; column=column (Ranger ID: 4)
-- Type: GRANT | Principal: user3
-- ═══════════════════════════════════════════════════════
-- ⚠ COLUMN-SCOPED GRANT WIDENED TO TABLE LEVEL
-- Original Ranger grant was limited to column(s): column
-- Unity Catalog has no column-level GRANT — privileges apply to the whole table.
-- If column-level restriction is required, apply column masks on the
-- other columns to return NULL/redacted values for non-permitted principals.
-- ⚠ CREATE privilege has no direct equivalent on a UC TABLE (Ranger 'create' at table scope). Grant MODIFY for write access, or ALL PRIVILEGES for full control.
-- ⚠ DROP privilege has no direct equivalent in Unity Catalog. Converted to MANAGE (allows managing grants on the object). To allow dropping the object, grant ALL PRIVILEGES or assign object ownership instead.
GRANT MANAGE ON TABLE `main`.`default`.`table` TO `user3@company.com`;
GRANT SELECT ON TABLE `main`.`default`.`table` TO `user3@company.com`;
