-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: atlasdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 5 of 5
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: policy for DataSets (Ranger ID: 1)
-- Type: GRANT | Principal: data-stewards
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ENTITY-READ) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `data-stewards`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `data-stewards`;
-- ⚠ 'ENTITY-READ' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: policy for hive_table (Ranger ID: 2)
-- Type: GRANT | Principal: hive-admins
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ENTITY-READ) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `hive-admins`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `hive-admins`;
-- ⚠ 'ENTITY-READ' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: policy for PII classification (Ranger ID: 10)
-- Type: GRANT | Principal: privacy-officers
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ENTITY-READ) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `privacy-officers`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `privacy-officers`;
-- ⚠ 'ENTITY-READ' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: policy for EMAIL_PII classification (Ranger ID: 20)
-- Type: GRANT | Principal: email-admins
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ENTITY-READ) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `email-admins`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `email-admins`;
-- ⚠ 'ENTITY-READ' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.

-- ═══════════════════════════════════════════════════════
-- Policy: policy for atlas resource matching (Ranger ID: 3)
-- Type: GRANT | Principal: group1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targeted table=* (all tables in `default`).
-- SELECT and MODIFY are table-level privileges in UC — they cannot be granted on SCHEMA.
-- They are applied via a BEGIN...END FOR loop over all tables in the schema.
-- Other privileges (ENTITY-READ) are granted directly on the schema.
GRANT USE CATALOG ON CATALOG `main` TO `group1`;
GRANT USE SCHEMA ON SCHEMA `main`.`default` TO `group1`;
-- ⚠ 'ENTITY-READ' is a Ranger/service-specific privilege with no Unity Catalog equivalent. No GRANT is emitted. Review manually.
