-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: awsdev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 13 of 13
-- ╚═══════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 / (Ranger ID: 10)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_root>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_root>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /home/ (Ranger ID: 20)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /home/
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_home>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_home>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmpa/b (Ranger ID: 30)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmpa/b
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmpa_b>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmpa_b>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmp/ab (Ranger ID: 40)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmp/ab
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmp_ab>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmp_ab>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmp/a/b (Ranger ID: 50)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmp/a/b
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmp_a_b>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmp_a_b>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmp/ac/d/e/f (Ranger ID: 60)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmp/ac/d/e/f
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmp_ac_d_e_f>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmp_ac_d_e_f>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmpfile (Ranger ID: 70)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmpfile
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmpfile>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmpfile>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-user1 /tmp.txt (Ranger ID: 80)
-- Type: HDFS_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- HDFS path: /tmp.txt
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_tmp_txt>` TO `user1@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_tmp_txt>` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-/tmp/{USER}} (Ranger ID: 100)
-- Type: HDFS_GRANT | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ PRINCIPAL NOT TRANSLATED — Ranger {USER} wildcard
-- Policy: allow-read-to-/tmp/{USER}}
-- Resource: `main`
-- Original principal: {USER}
--
-- {USER} is a Ranger placeholder meaning 'the currently authenticated user'.
-- It cannot be used as a named principal in a UC GRANT statement.
--
-- If the intent is 'grant to all users': use GRANT ... TO `account users`.
-- If the intent is 'row/column access based on the calling user': express
-- the logic in a row filter or column mask using current_user().

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-/tmp/{USER}/subdir} (Ranger ID: 200)
-- Type: HDFS_GRANT | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ PRINCIPAL NOT TRANSLATED — Ranger {USER} wildcard
-- Policy: allow-all-to-/tmp/{USER}/subdir}
-- Resource: `main`
-- Original principal: {USER}
--
-- {USER} is a Ranger placeholder meaning 'the currently authenticated user'.
-- It cannot be used as a named principal in a UC GRANT statement.
--
-- If the intent is 'grant to all users': use GRANT ... TO `account users`.
-- If the intent is 'row/column access based on the calling user': express
-- the logic in a row filter or column mask using current_user().

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-/user/dir} (Ranger ID: 300)
-- Type: HDFS_GRANT | Principal: scott
-- ═══════════════════════════════════════════════════════
-- HDFS path: /user/dir (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_user_dir>` TO `scott@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-all-to-/user/dir/subdir} (Ranger ID: 400)
-- Type: HDFS_GRANT | Principal: scott
-- ═══════════════════════════════════════════════════════
-- HDFS path: /user/dir/subdir (recursive)
-- ⚠ Create a UC External Location covering this path first,
--   then replace the placeholder below with the actual location name.
GRANT READ FILES ON EXTERNAL LOCATION `<ext_loc_user_dir_subdir>` TO `scott@company.com`;
GRANT WRITE FILES ON EXTERNAL LOCATION `<ext_loc_user_dir_subdir>` TO `scott@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: allow-read-to-/user/{USER}/a*} (Ranger ID: 500)
-- Type: HDFS_GRANT | Principal: {USER}
-- ═══════════════════════════════════════════════════════
-- ⛔ PRINCIPAL NOT TRANSLATED — Ranger {USER} wildcard
-- Policy: allow-read-to-/user/{USER}/a*}
-- Resource: `main`
-- Original principal: {USER}
--
-- {USER} is a Ranger placeholder meaning 'the currently authenticated user'.
-- It cannot be used as a named principal in a UC GRANT statement.
--
-- If the intent is 'grant to all users': use GRANT ... TO `account users`.
-- If the intent is 'row/column access based on the calling user': express
-- the logic in a row filter or column mask using current_user().
