-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: hivedev
-- ║  Target Catalog: main
-- ║  Date: 2026-06-02
-- ║  Policies: 11 of 11
-- ╚═══════════════════════════════════════════════════════════╝

-- ⚠ CONFLICT NOTICE: 1 row-filter/column-mask conflict(s) detected.
-- Unity Catalog supports only ONE row filter per table and ONE mask per column.
-- Conflicting items have been automatically MERGED into combined CASE functions below.
-- Review each merged function carefully before executing.

-- ═══════════════════════════════════════════════════════
-- ⚠ MERGED COLUMN MASK — Unity Catalog supports only ONE mask per column.
-- Multiple Ranger principals for `employee`.`personal`.ssn have been combined.
-- Principals merged (2): user1@company.com, user3@company.com
-- Function parameter is STRING. If the actual column type differs, adjust the signature.

CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_ssn(val STRING)
RETURNS STRING
RETURN
  CASE
    WHEN current_user() = 'user1@company.com' THEN '***REDACTED***'
    WHEN current_user() = 'user3@company.com' THEN '***REDACTED***'
    ELSE val  -- no masking for other principals
  END;

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN ssn SET MASK `main`.`employee`.mask_personal_ssn;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `public`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `hive@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user1@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*: audit-all-access (Ranger ID: 101)
-- Type: GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ranger policy targets database=* (all schemas in the cluster).
-- UC equivalent is a catalog-level grant on `main`.
-- Only USE CATALOG, CREATE SCHEMA, and ALL PRIVILEGES are valid at catalog level.
-- Other privileges (SELECT, MODIFY, etc.) must be granted per-schema or per-table.
GRANT USE CATALOG ON CATALOG `main` TO `user2@company.com`;
GRANT ALL PRIVILEGES ON CATALOG `main` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: public
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `public`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: hive
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `hive@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user1
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user1@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: db=*, udf=*: audit-all-access (Ranger ID: 102)
-- Type: UDF_GRANT | Principal: user2
-- ═══════════════════════════════════════════════════════
-- ⚠ Ensure function main.*.* is registered in UC before granting.
GRANT EXECUTE ON FUNCTION `main`.`*`.`*` TO `user2@company.com`;

-- ═══════════════════════════════════════════════════════
-- Policy: masking: employee.personal.name - normal priority (Ranger ID: 105)
-- Type: COLUMN_MASK | Principal: user1
-- ═══════════════════════════════════════════════════════
-- Column Mask: Full redaction for user1@company.com
CREATE OR REPLACE FUNCTION `main`.`employee`.mask_personal_name_user1_company_com(val STRING)
RETURNS STRING
RETURN IF(
  current_user() = 'user1@company.com',
  '***REDACTED***',
  val
);

ALTER TABLE `main`.`employee`.`personal`
ALTER COLUMN name SET MASK `main`.`employee`.mask_personal_name_user1_company_com;
