-- ╔═══════════════════════════════════════════════════════════╗
-- ║  Unity Catalog Migration Script                          ║
-- ║  Generated by Ranger → UC Migrator                       ║
-- ║  Source: updated-hbase-test-policies
-- ║  Target Catalog: main
-- ║  Date: 2026-05-31
-- ║  Policies: 0 of 0
-- ╚═══════════════════════════════════════════════════════════╝

