"""Catalog of Ranger policy sample files shared with ranger-uc-translator."""
from __future__ import annotations

import json
import os

SAMPLES_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "input")

SAMPLE_FILES: list[dict] = [
    # ── Cloudera CDP ──────────────────────────────────────────────────
    {
        "filename": "cloudera_15policy_sample.json",
        "display_name": "Cloudera CDP 7.1 – 15 policies (all types)",
        "description": "Realistic Cloudera CDP production export: grants, deny, row filters, and column masks across finance, HR, marketing, supply-chain, and compliance domains.",
        "service": "cl1_hive_production",
        "service_type": "hive",
        "policy_count": 15,
        "category": "Cloudera CDP",
        "tags": ["grant", "deny", "row_filter", "column_mask"],
    },
    # ── Access (grant) samples ────────────────────────────────────────
    {
        "filename": "access_simple.json",
        "display_name": "Access – Simple (1 policy)",
        "description": "Single SELECT grant for an analyst on a customers table.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Access",
        "tags": ["grant"],
    },
    {
        "filename": "access_medium.json",
        "display_name": "Access – Medium (1 policy)",
        "description": "Sales team full-access grant on a sales schema with multiple groups.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Access",
        "tags": ["grant"],
    },
    {
        "filename": "access_complex.json",
        "display_name": "Access – Complex (1 policy)",
        "description": "Multi-group, multi-privilege grant with delegateAdmin across several tables.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Access",
        "tags": ["grant", "delegateAdmin"],
    },
    # ── Column masking samples ────────────────────────────────────────
    {
        "filename": "masking_simple.json",
        "display_name": "Column Mask – Simple (1 policy)",
        "description": "Basic hash masking on a single PII column for one group.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Column Masking",
        "tags": ["column_mask"],
    },
    {
        "filename": "masking_medium.json",
        "display_name": "Column Mask – Medium (1 policy)",
        "description": "Tiered masking (NONE / LAST_4 / HASH) across two groups on an employee table.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Column Masking",
        "tags": ["column_mask"],
    },
    {
        "filename": "masking_complex.json",
        "display_name": "Column Mask – Complex (1 policy)",
        "description": "Multi-column masking with expression-based and null-out rules for several principals.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Column Masking",
        "tags": ["column_mask"],
    },
    # ── Row filter samples ────────────────────────────────────────────
    {
        "filename": "rowfilter_simple.json",
        "display_name": "Row Filter – Simple (1 policy)",
        "description": "Single-group row-level filter with a plain equality expression.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Row Filters",
        "tags": ["row_filter"],
    },
    {
        "filename": "rowfilter_medium.json",
        "display_name": "Row Filter – Medium (1 policy)",
        "description": "Regional row filters for marketing teams (APAC / EMEA / Americas).",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Row Filters",
        "tags": ["row_filter"],
    },
    {
        "filename": "rowfilter_complex.json",
        "display_name": "Row Filter – Complex (1 policy)",
        "description": "Multi-group row filters with IN, LIKE, and compound expressions.",
        "service": "hive_prod",
        "service_type": "hive",
        "policy_count": 1,
        "category": "Row Filters",
        "tags": ["row_filter"],
    },
    # ── Tag-based policy samples ──────────────────────────────────────
    {
        "filename": "tag_simple.json",
        "display_name": "Tag Policy – Simple (1 policy)",
        "description": "Single tag-based access policy on a classified dataset.",
        "service": "tag_prod",
        "service_type": "tag",
        "policy_count": 1,
        "category": "Tag Policies",
        "tags": ["grant", "tag"],
    },
    {
        "filename": "tag_medium.json",
        "display_name": "Tag Policy – Medium (2 policies)",
        "description": "Two tag-based policies covering grant and deny on tagged resources.",
        "service": "tag_prod",
        "service_type": "tag",
        "policy_count": 2,
        "category": "Tag Policies",
        "tags": ["grant", "deny", "tag"],
    },
    {
        "filename": "tag_complex.json",
        "display_name": "Tag Policy – Complex (2 policies)",
        "description": "Complex tag policies with multiple groups and condition expressions.",
        "service": "tag_prod",
        "service_type": "tag",
        "policy_count": 2,
        "category": "Tag Policies",
        "tags": ["grant", "deny", "tag"],
    },
    # ── Hive engine samples ───────────────────────────────────────────
    {
        "filename": "test_policyengine_hive.json",
        "display_name": "Hive – Policy Engine (12 policies)",
        "description": "Full Hive policy engine test suite: grants, deny, database/table/column scope.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 12,
        "category": "Hive",
        "tags": ["grant", "deny"],
    },
    {
        "filename": "test_policyengine_hive_default_policies.json",
        "display_name": "Hive – Default Policies (4 policies)",
        "description": "Default Ranger Hive policies created on a fresh service (public/all access patterns).",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 4,
        "category": "Hive",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hive_mask_filter.json",
        "display_name": "Hive – Mask + Row Filter (5 policies)",
        "description": "Hive policies combining column masking and row-level filtering on the same service.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 5,
        "category": "Hive",
        "tags": ["grant", "column_mask", "row_filter"],
    },
    {
        "filename": "test_policyengine_hive_mask_filter_with_req_expressions.json",
        "display_name": "Hive – Mask + Filter with Expressions (3 policies)",
        "description": "Mask and row-filter policies that use request-attribute condition expressions.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 3,
        "category": "Hive",
        "tags": ["column_mask", "row_filter"],
    },
    {
        "filename": "test_policyengine_hive_mutex_conditions.json",
        "display_name": "Hive – Mutex Conditions (3 policies)",
        "description": "Hive policies with mutually exclusive condition blocks for context-based access.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 3,
        "category": "Hive",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hive_with_partial_resource_policies.json",
        "display_name": "Hive – Partial Resource Policies (4 policies)",
        "description": "Hive grants that target partial resource paths (database-only or table-only).",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 4,
        "category": "Hive",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hive_incremental_add.json",
        "display_name": "Hive – Incremental Add (3 policies)",
        "description": "Hive incremental policy set: policies added via delta to an existing service.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 3,
        "category": "Hive",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_hive_incremental_delete.json",
        "display_name": "Hive – Incremental Delete (4 policies)",
        "description": "Hive incremental policy set: policies removed via delta from an existing service.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 4,
        "category": "Hive",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_hive_incremental_update.json",
        "display_name": "Hive – Incremental Update (4 policies)",
        "description": "Hive incremental policy set: policies updated in-place via delta.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 4,
        "category": "Hive",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_with_roles.json",
        "display_name": "Hive – With Roles (3 policies)",
        "description": "Hive policies that use Ranger roles to group principals for access control.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 3,
        "category": "Hive",
        "tags": ["grant", "roles"],
    },
    # ── Tag + Hive samples ────────────────────────────────────────────
    {
        "filename": "test_policyengine_tag_hive.json",
        "display_name": "Hive – Tag-Based Access (4 policies)",
        "description": "Hive policies driven by Atlas tags for attribute-based access control.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 4,
        "category": "Hive",
        "tags": ["grant", "tag"],
    },
    {
        "filename": "test_policyengine_tag_hive_mask.json",
        "display_name": "Hive – Tag-Based Masking (5 policies)",
        "description": "Column masking policies applied via Atlas tag classification.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 5,
        "category": "Hive",
        "tags": ["column_mask", "tag"],
    },
    {
        "filename": "test_policyengine_tag_hive_filebased.json",
        "display_name": "Hive – Tag File-Based (2 policies)",
        "description": "Tag policies loaded from a file-based store rather than Atlas.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 2,
        "category": "Hive",
        "tags": ["grant", "tag"],
    },
    {
        "filename": "test_policyengine_tag_hive_for_show_databases.json",
        "display_name": "Hive – Tag Show Databases (2 policies)",
        "description": "Tag policies covering SHOW DATABASES access via tag classification.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 2,
        "category": "Hive",
        "tags": ["grant", "tag"],
    },
    # ── HDFS samples ──────────────────────────────────────────────────
    {
        "filename": "test_policyengine_hdfs.json",
        "display_name": "HDFS – Policy Engine (9 policies)",
        "description": "Core HDFS path-based access policies for users and groups.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 9,
        "category": "HDFS",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hdfs_allaudit.json",
        "display_name": "HDFS – All Audit (3 policies)",
        "description": "HDFS policies with audit logging enabled on every access event.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 3,
        "category": "HDFS",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hdfs_noaudit.json",
        "display_name": "HDFS – No Audit (3 policies)",
        "description": "HDFS policies with audit logging explicitly disabled.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 3,
        "category": "HDFS",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hdfs_multiple_accesses.json",
        "display_name": "HDFS – Multiple Access Types (6 policies)",
        "description": "HDFS policies exercising read, write, execute, and compound access types.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 6,
        "category": "HDFS",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hdfs_resourcespec.json",
        "display_name": "HDFS – Resource Spec (2 policies)",
        "description": "HDFS policies using recursive and exclusive path specifications.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 2,
        "category": "HDFS",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hdfs_zones.json",
        "display_name": "HDFS – Security Zones (3 policies)",
        "description": "HDFS policies scoped to Ranger security zones for zone-isolated access.",
        "service": "cl1_hadoop",
        "service_type": "hdfs",
        "policy_count": 3,
        "category": "HDFS",
        "tags": ["grant", "zones"],
    },
    {
        "filename": "test_policyengine_hdfs_incremental_delete.json",
        "display_name": "HDFS – Incremental Delete (2 policies)",
        "description": "HDFS incremental policy delta: policies removed from an existing service.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 2,
        "category": "HDFS",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_hdfs_incremental_update.json",
        "display_name": "HDFS – Incremental Update (2 policies)",
        "description": "HDFS incremental policy delta: policies updated in-place.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 2,
        "category": "HDFS",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_hdfs_incremental_update_for_wildcard_evaluators.json",
        "display_name": "HDFS – Incremental Update Wildcard (2 policies)",
        "description": "HDFS incremental update with wildcard path evaluators.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 2,
        "category": "HDFS",
        "tags": ["grant", "incremental"],
    },
    {
        "filename": "test_policyengine_tag_hdfs.json",
        "display_name": "HDFS – Tag-Based (3 policies)",
        "description": "HDFS path-access policies driven by Atlas tag classification.",
        "service": "hdfsdev",
        "service_type": "hdfs",
        "policy_count": 3,
        "category": "HDFS",
        "tags": ["grant", "tag"],
    },
    {
        "filename": "test_policyengine_aws.json",
        "display_name": "HDFS – AWS (13 policies)",
        "description": "HDFS-style access policies for an AWS-hosted Ranger cluster.",
        "service": "awsdev",
        "service_type": "hdfs",
        "policy_count": 13,
        "category": "HDFS",
        "tags": ["grant"],
    },
    # ── HBase samples ─────────────────────────────────────────────────
    {
        "filename": "hbase-test-policies.json",
        "display_name": "HBase – Full Suite (19 policies)",
        "description": "Comprehensive HBase policy set covering table, column-family, and row-level access.",
        "service": "cm_hbase",
        "service_type": "hbase",
        "policy_count": 19,
        "category": "HBase",
        "tags": ["grant", "deny"],
    },
    {
        "filename": "test_policyengine_hbase.json",
        "display_name": "HBase – Policy Engine (3 policies)",
        "description": "Core HBase policy engine test: table and column-family grants.",
        "service": "hbasedev",
        "service_type": "hbase",
        "policy_count": 3,
        "category": "HBase",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hbase_multiple_matching_policies.json",
        "display_name": "HBase – Multiple Matching (2 policies)",
        "description": "HBase scenario where multiple policies match the same resource.",
        "service": "hbasedev",
        "service_type": "hbase",
        "policy_count": 2,
        "category": "HBase",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_hbase_namespace.json",
        "display_name": "HBase – Namespace Policies (2 policies)",
        "description": "HBase policies scoped to namespace-level access control.",
        "service": "hbasedev",
        "service_type": "hbase",
        "policy_count": 2,
        "category": "HBase",
        "tags": ["grant"],
    },
    {
        "filename": "test_policyengine_tag_hbase.json",
        "display_name": "HBase – Tag-Based (2 policies)",
        "description": "HBase table access governed by Atlas tag classification.",
        "service": "hbasedev",
        "service_type": "hbase",
        "policy_count": 2,
        "category": "HBase",
        "tags": ["grant", "tag"],
    },
    # ── ACL Provider tests ────────────────────────────────────────────
    {
        "filename": "test_aclprovider_default.json",
        "display_name": "ACL Provider – Default Hive (20 access + 5 tag policies)",
        "description": "Full ACL provider test suite for Hive: grants, deny, and tag-based policies across databases and tables.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 25,
        "category": "ACL Provider Tests",
        "tags": ["grant", "deny", "tag"],
    },
    {
        "filename": "test_aclprovider_hdfs.json",
        "display_name": "ACL Provider – HDFS (4 policies)",
        "description": "ACL provider test for HDFS path-based access with read, write, and execute types.",
        "service": "hivedev",
        "service_type": "hdfs",
        "policy_count": 4,
        "category": "ACL Provider Tests",
        "tags": ["grant"],
    },
    {
        "filename": "test_aclprovider_mask_filter.json",
        "display_name": "ACL Provider – Mask + Row Filter (11 access + 3 tag policies)",
        "description": "ACL provider test combining column masking and row-level filtering with tag-based policies.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 14,
        "category": "ACL Provider Tests",
        "tags": ["column_mask", "row_filter", "tag"],
    },
    {
        "filename": "test_aclprovider_resource_hierarchy_tags.json",
        "display_name": "ACL Provider – Resource Hierarchy Tags (9 tag policies)",
        "description": "ACL provider test focused on tag-based policies with resource hierarchy resolution.",
        "service": "hivedev",
        "service_type": "hive",
        "policy_count": 9,
        "category": "ACL Provider Tests",
        "tags": ["tag"],
    },
    # ── Other services ────────────────────────────────────────────────
    {
        "filename": "test_policyengine_kafka.json",
        "display_name": "Kafka – Policy Engine (14 policies)",
        "description": "Kafka topic and consumer-group access policies (produce/consume/describe).",
        "service": "kafkadev",
        "service_type": "kafka",
        "policy_count": 14,
        "category": "Other Services",
        "tags": ["grant", "deny"],
    },
    {
        "filename": "test_policyengine_atlas.json",
        "display_name": "Atlas – Policy Engine (5 policies)",
        "description": "Apache Atlas entity and classification access policies.",
        "service": "atlasdev",
        "service_type": "atlas",
        "policy_count": 5,
        "category": "Other Services",
        "tags": ["grant"],
    },
]


def load_sample(filename: str) -> dict:
    """Load a sample JSON file by filename from SAMPLES_DIR."""
    path = os.path.join(SAMPLES_DIR, filename)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_sample_meta(filename: str) -> dict | None:
    for s in SAMPLE_FILES:
        if s["filename"] == filename:
            return s
    return None
